---
title: "Indicators"
author: "Christian Kruse"
date: "4/6/2022"
output: html_document
---

```{r  include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
options(scipen=999)
```

```{r}

if (!require(pacman)) { install.packages("pacman") }
pacman::p_load(fredr,
               dplyr,
               tidyr,
               lubridate,
               caret,
               partykit,
               pROC,
               gganimate,
               devtools,
               irr,
               httr,
               data.table,
               pROC,
               progress,
               rvest,
               ggrepel)
source(file = "money_theme.R")
```

# FED: Release Calendar

```{r }
readRenviron(path = "Renviron.site")
fredr::fredr_set_key(key = Sys.getenv("FRED_API"))
```

```{r}

add_fomc_meeting_dates = function() {
  geom_vline(xintercept = c(ymd("2022-06-15"),
                            ymd("2022-07-27"),
                            ymd("2022-09-21"),
                            ymd("2022-11-02"),
                            ymd("2022-12-14"),
                            ymd("2023-02-01"),
                            ymd("2023-03-15"),
                            ymd("2023-05-03"),
                            ymd("2023-06-14"),
                            ymd("2023-07-26")),linetype=2,color="#eb493a")
}
```


```{r}


fredr::fredr_releases_dates(realtime_start = Sys.Date(),
                            realtime_end = Sys.Date()+months(1),
                            limit = 1000,
                            include_release_dates_with_no_data=TRUE) %>% 
  dplyr::mutate(date=ymd(date)) %>% 
  dplyr::mutate(days_from_now=as.numeric(date-Sys.Date()),
                date_label=format.Date(date,"%A %d/%m")) %>% 
  group_by(release_name) %>% 
  filter(date==min(date)) %>% 
  dplyr::select(date_label,days_from_now,release_name,release_id) %>% 
  arrange(days_from_now) %>% 
  DT::datatable()

```


```{r}

fredr::fredr_tags_series(tag_names = "nsa",order_by = "popularity",sort_order = "desc")

```


```{r}

df_NASDAQCOM = fredr::fredr_series_observations(series_id = "NASDAQCOM") %>% 
  dplyr::select(date,value)

df_T10Y2Y = fredr::fredr_series_observations(series_id = "T10Y2Y") %>%  
  dplyr::select(date,value) 

df_joined = df_NASDAQCOM %>% 
  inner_join(df_T10Y2Y,by=c("date"))

df_joined %>% 
  ggplot(.,aes(x=value.x,y=value.y)) +
  geom_point() +
  geom_smooth(method="glm")



df_cor = rbindlist(lapply(seq(-5000,5000,by=10),function(day) {
  temp_df = df_NASDAQCOM %>% 
    dplyr::mutate(join_date=date+days(day)) %>% 
    inner_join(df_T10Y2Y,by=c("join_date"="date"))
  
  data.frame(day=day,
             cor=cor(x=temp_df$value.x,y=temp_df$value.y,use = "complete.obs"))
  
}))

ggplot(df_cor,aes(x=day,y=cor)) +
  geom_point()

df_NASDAQCOM %>% 
  dplyr::mutate(join_date=date+days(-3000)) %>% 
  inner_join(df_T10Y2Y,by=c("join_date"="date")) %>% 
  ggplot(.,aes(x=value.x,y=value.y)) +
  geom_point() +
  geom_smooth(method="lm")
```



```{r}
series_ids = c("CBBTCUSD",
               "NASDAQCOM",
               "T10Y2Y",
               "T5YIFR",
               "BAA10Y",
               "T10Y3M",
               "CPIAUCSL",
               "DCOILWTICO",
               "DFF",
               "MORTGAGE30US",
               "BAMLH0A0HYM2",
               "T10YIE",
               "T10Y3M",
               "UNRATE",
               "DGS10",
               "CSUSHPINSA",
               "GDP",
               "GDPC1",
               "DFII10",
               "MSPUS")

df_series = rbindlist(lapply(series_ids,function(series_id) {
  fredr::fredr_series_observations(series_id = series_id) %>% 
  dplyr::select(date,value) %>% 
    dplyr::mutate(series_id=series_id)
}))

combinations = data.frame(t(combn(series_ids,2)))
combinations = expand.grid(x1=series_ids,
            x2=series_ids) %>% 
  filter(x1!=x2)

```


```{r}

# All
df_correlations = rbindlist(apply(combinations,1,function(series) {
    tryCatch(expr = {
      x = series[[1]]
      y = series[[2]]
      values_x = df_series[which(df_series$series_id==x),]
      values_y = df_series[which(df_series$series_id==y),]
      temp_df = values_x %>% 
        left_join(values_y,by=c("date")) %>% 
        fill(c(value.x,value.y),.direction = "downup")
      cor_= cor(x = temp_df$value.x,y = temp_df$value.y,use = "complete.obs")
      data.frame(X1=x,X2=y,correlation=cor_)
  },error=function(e) { data.frame()})
}))

df_correlations
```


```{r}
# Time-dependent
df_correlations_timeadjusted = rbindlist(apply(combinations,1,function(series) {
  tryCatch(expr = {
      x = series[[1]]
      y = series[[2]]
      # message(paste0(x,"-",y))
      values_x = df_series[which(df_series$series_id==x),]
      values_y = df_series[which(df_series$series_id==y),]
      
      df_cor = rbindlist(lapply(seq(-3*365,3*365,by=10),function(day) {
            temp_df = values_x %>% 
                    dplyr::mutate(join_date=date+days(day)) %>% 
                    left_join(values_y,by=c("join_date"="date")) %>% 
                    fill(c(value.x,value.y),.direction = "downup")
            data.frame(day=day,
                       cor=cor(x=temp_df$value.x,
                               y=temp_df$value.y,
                               use = "complete.obs"))
          
        }))
      
      min_ = which(df_cor$cor==min(df_cor$cor))
      max_ = which(df_cor$cor==max(df_cor$cor))
      
      data.frame(X1=x,X2=y,
                 min=min_,min_cor=df_cor[min_]$cor,
                 max=max_,max_cor=df_cor[max_]$cor)
  },error=function(e) { data.frame()})
}))

df_correlations_timeadjusted
```

```{r}
## Draw plot

x1 = "NASDAQCOM"
x2 = "DFII10"
days = 97

# message(paste0(x,"-",y))
values_x = df_series[which(df_series$series_id==x1),]
values_y = df_series[which(df_series$series_id==x2),]

# Facetted
df_series %>% 
  filter(series_id %in% c(x1,x2)) %>% 
  group_by(series_id) %>%
  # dplyr::mutate(value=scale(value)) %>%
  # dplyr::mutate(value=scales::rescale(value,to = c(0,100))) %>% 
  # ungroup() %>%
  ggplot(.,aes(x=date,y=value,color=series_id)) +
  geom_line() +
  facet_wrap(~series_id,ncol=1,scales="free")


temp_df = values_x %>% 
        dplyr::mutate(join_date=date+days(days)) %>% 
        left_join(values_y,by=c("join_date"="date")) %>% 
        fill(c(value.x,value.y),.direction = "downup")

temp_df %>% 
  ggplot(.,aes(x=value.x,y=value.y)) +
  geom_point() +
  geom_smooth(method="lm")
          

```



# FED

```{r }
readRenviron(path = "Renviron.site")
fredr::fredr_set_key(key = Sys.getenv("FRED_API"))

```

```{r }

df_yieldcurve = 
  fredr(series_id = "DGS1") %>% 
  bind_rows(fredr(series_id = "DGS2")) %>% 
  bind_rows(fredr(series_id = "DGS3")) %>% 
  bind_rows(fredr(series_id = "DGS5")) %>% 
  bind_rows(fredr(series_id = "DGS7")) %>% 
  bind_rows(fredr(series_id = "DGS10")) %>% 
  bind_rows(fredr(series_id = "DGS20")) %>% 
  bind_rows(fredr(series_id = "DGS30")) %>% 
  bind_rows(fredr(series_id = "DGS1MO")) %>% 
  bind_rows(fredr(series_id = "DGS3MO")) %>% 
  bind_rows(fredr(series_id = "DGS6MO")) %>% 
  bind_rows(fredr(series_id = "DFF")) %>% 
  bind_rows(fredr(series_id = "MORTGAGE30US")) %>% 
  bind_rows(fredr(series_id = "WILL5000INDFC")) %>% 
  bind_rows(fredr(series_id = "DCOILWTICO")) %>% 
  bind_rows(fredr(series_id = "SP500")) %>% 
  bind_rows(fredr(series_id = "T10Y2Y")) %>% 
  bind_rows(fredr(series_id = "T10YIE")) %>% 
  bind_rows(fredr(series_id = "DTWEXBGS")) %>% 
  bind_rows(fredr(series_id = "DHHNGSP")) %>% 
  
  bind_rows(fredr(series_id = "MSPUS")) %>% 
  bind_rows(fredr(series_id = "CSUSHPINSA")) %>% 
  bind_rows(fredr(series_id = "UNRATE")) %>% 
  bind_rows(fredr(series_id = "M2SL")) %>% 
  bind_rows(fredr(series_id = "CPIAUCSL")) %>% 
  bind_rows(fredr(series_id = "BAMLH0A0HYM2")) %>% 
  bind_rows(fredr(series_id = "CIVPART")) %>% 
  bind_rows(fredr(series_id = "PCE")) %>% 
  bind_rows(fredr(series_id = "MSACSR")) %>% 
  bind_rows(fredr(series_id = "PSAVERT")) %>% 
  bind_rows(fredr(series_id = "AAA")) %>% 
  # bind_rows(fredr(series_id = "AAA")) %>% 
  # bind_rows(fredr(series_id = "AAA")) %>% 
  # bind_rows(fredr(series_id = "AAA")) %>% 
  # bind_rows(fredr(series_id = "AAA")) %>% 
  # bind_rows(fredr(series_id = "AAA")) %>% 
  
  
  group_by(series_id) %>% 
  tidyr::complete(date=seq.Date(from = min(date), to = max(date), by = "1 day")) %>% 
  arrange(series_id,date) %>% 
  tidyr::fill(value,.direction = "downup") %>% 
  ungroup() %>% 
  na.omit() %>% 
  dplyr::select(date,series_id,value)

df_combinations = expand.grid(series_id=unique(df_yieldcurve$series_id),
            joined_series_id=unique(df_yieldcurve$series_id)) %>% 
  filter(!series_id==joined_series_id)
# unique(df_yieldcurve$series_id)
# df_combinations = data.frame(t(combn(unique(df_yieldcurve$series_id),2))) %>% 
#   setNames(.,c("series_id","joined_series_id"))
```

# LM Regression

```{r}

calc_rsq = function(data) {
  return( data.frame(rsq=summary( lm(value.x~value.y,data=data) )$r.squared) )
}
years = 2

# diffs = sort(c(0,seq(-1000,1000,by=30)))
diffs = sort(c(0,seq(-years*365,years*365,by=90)))
pb <- progress_bar$new(format = "  Calculating [:bar] :percent eta: :eta",
                       total = length(diffs))

df_kappa = rbindlist(lapply(diffs,function(days_diff) {
  pb$tick()
  # message(days_diff)
  df_combinations %>% 
  inner_join(df_yieldcurve,by=c("series_id"="series_id")) %>% 
  dplyr::mutate(date=date+days(days_diff)) %>% 
  inner_join(df_yieldcurve,by=c("joined_series_id"="series_id","date"="date")) %>% 
  dplyr::select(date , series_id , joined_series_id , value.x , value.y) %>% 
  group_by(series_id,joined_series_id) %>% 
  do(calc_rsq(.)) %>% 
  dplyr::mutate(days_diff=days_diff) %>% 
  ungroup()# %>% 
  # unite(series_id,series_id,joined_series_id)
})) #%>% 
  # separate(series_id,into=c("series1","series2"))

df_kappa_2 = df_kappa %>% 
  rename(series1=series_id,
         series2=joined_series_id)

```

```{r}

indicator = "WILL5000INDFC"

# Current Indicator
tmp_current = df_kappa_2 %>% 
  filter(series1 == indicator) %>% 
  filter(days_diff==80)

tmp_current %>% 
  arrange(rsq) %>% 
  dplyr::mutate(series2=factor(series2,levels=.$series2)) %>% 
  ggplot(.,aes(x=series2,y=rsq)) +
  geom_point() +
  coord_flip() +
  geom_hline(yintercept = 0,linetype=2) +
  scale_y_continuous(limits = c(-1,1),breaks=seq(-1,1,by=0.1))

```

```{r}

df_example = df_combinations %>% 
  filter(series_id=="WILL5000INDFC") %>% 
  filter(joined_series_id=="CPIAUCSL") %>% 
  inner_join(df_yieldcurve,by=c("series_id"="series_id")) %>% 
  inner_join(df_yieldcurve,by=c("joined_series_id"="series_id","date"="date")) %>% 
  dplyr::select(date , series_id , joined_series_id , value.x , value.y) %>% 
  dplyr::mutate(value.x=100*value.x/first(value.x)) %>% 
  dplyr::mutate(value.y=100*value.y/first(value.y))


```

```{r}

calc_cor = function(data) {
  return( data.frame(cor=cor(x = data$value.x, y = data$value.y) ) )
}
years = 3

# diffs = sort(c(0,seq(-1000,1000,by=30)))
diffs = sort(c(0,seq(-years*365,years*365,by=90)))
pb <- progress_bar$new(format = "  Calculating [:bar] :percent eta: :eta",
                       total = length(diffs))

df_kappa = rbindlist(lapply(diffs,function(days_diff) {
  pb$tick()
  # message(days_diff)
  df_combinations %>% 
  inner_join(df_yieldcurve,by=c("series_id"="series_id")) %>% 
  dplyr::mutate(date=date+days(days_diff)) %>% 
  inner_join(df_yieldcurve,by=c("joined_series_id"="series_id","date"="date")) %>% 
  dplyr::select(date , series_id , joined_series_id , value.x , value.y) %>% 
  group_by(series_id,joined_series_id) %>% 
  do(calc_cor(.)) %>% 
  dplyr::mutate(days_diff=days_diff) %>% 
  ungroup()# %>% 
  # unite(series_id,series_id,joined_series_id)
})) #%>% 
  # separate(series_id,into=c("series1","series2"))

df_kappa = df_kappa %>% 
  rename(series1=series_id,
         series2=joined_series_id)

```

# Example

```{r}



indicator = "UNRATE"

# Current Indicator
tmp_current = df_kappa %>% 
  filter(series1 == indicator) %>% 
  filter(days_diff==0)

tmp_current %>% 
  arrange(cor) %>% 
  dplyr::mutate(series2=factor(series2,levels=.$series2)) %>% 
  ggplot(.,aes(x=series2,y=cor)) +
  geom_point() +
  coord_flip() +
  geom_hline(yintercept = 0,linetype=2) +
  scale_y_continuous(limits = c(-1,1),breaks=seq(-1,1,by=0.1))

# All Times
tmp_all = df_kappa %>% 
  filter(series1 == indicator) %>% 
  # filter(days_diff>0) %>% 
  group_by(series2) %>% 
  dplyr::mutate(label_=ifelse(days_diff==max(days_diff),series2,NA)) %>% 
  ungroup()

tmp_all %>% 
  ggplot(.,aes(x=days_diff,y=cor,color=series2)) +
  geom_point() +
  geom_line() +
  # coord_flip() +
  geom_hline(yintercept = 0,linetype=2) +
  theme(legend.position="null") +
  scale_x_continuous(expand=expansion(mult=c(0.1,0.1))) +
  geom_text_repel(aes(label=label_),nudge_x = 50)


# Leading Indicator
tmp_leading = df_kappa %>% 
  filter(series1 == indicator) %>% 
  filter(days_diff>0) %>% 
  group_by(series2) %>% 
  dplyr::mutate(label_=ifelse(days_diff==max(days_diff),series2,NA)) %>% 
  ungroup()

tmp_leading %>% 
  ggplot(.,aes(x=days_diff,y=cor,color=series2)) +
  geom_point() +
  geom_line() +
  # coord_flip() +
  geom_hline(yintercept = 0,linetype=2) +
  theme(legend.position="null") +
  scale_x_continuous(expand=expansion(mult=c(0.1,0.1)),breaks = seq(-10,10)*180) +
  geom_text_repel(aes(label=label_),nudge_x = 50)

# Lagging Indicator
tmp_lagging = df_kappa %>% 
  filter(series1 == indicator) %>% 
  filter(days_diff<0)

tmp_lagging %>% 
  ggplot(.,aes(x=days_diff,y=cor,color=series2)) +
  geom_point() +
  geom_line() +
  # coord_flip() +
  geom_hline(yintercept = 0,linetype=2)  +
  theme(legend.position="null")
```

```{r}

series1 = "WILL5000INDFC"
series2 = "CPIAUCSL"
time_diff = 0

tmp = df_combinations %>% 
  filter(series_id==series1,
         joined_series_id==series2) %>% 
  inner_join( df_yieldcurve , by = c("series_id"="series_id") ) %>% 
  inner_join( df_yieldcurve , by = c("date"="date","joined_series_id"="series_id") ) %>% 
  dplyr::mutate(new_date=date+days(time_diff)) %>% 
  inner_join( df_yieldcurve , by = c("joined_series_id"="series_id","new_date"="date") ) %>% 
  dplyr::select( date, value.x, value.y, value) %>% 
  setNames(.,c("date",series1,series2,paste0(series2,"_diff")))

# cor(tmp$WILL5000INDFC,tmp$DTWEXBGS)
# cor(tmp$WILL5000INDFC,tmp$DTWEXBGS_diff)

tmp %>% 
  gather(stat,val,2:4) %>% 
  group_by(stat) %>% 
  dplyr::mutate(val=scale(val)) %>% 
  ggplot(.,aes(x=date,y=val,color=stat)) + 
  geom_line()


```


# Multivariate

# Current Indicator

```{r}

series1 = "SP500"
time_diff = 0

df_lm = df_combinations %>% 
  filter(series_id==series1) %>% 
  inner_join( df_yieldcurve , by = c("series_id"="series_id") ) %>% 
  # inner_join( df_yieldcurve , by = c("date"="date","joined_series_id"="series_id") ) %>% 
  dplyr::mutate(new_date=date+days(time_diff)) %>% 
  inner_join( df_yieldcurve , by = c("joined_series_id"="series_id","new_date"="date") ) %>% 
  dplyr::select( date, series_id , joined_series_id, date , value.x, value.y) %>% 
  spread(joined_series_id,value.y) %>% 
  dplyr::select(-date,-series_id) 
  # setNames(.,c("date",series1,series2,paste0(series2,"_diff"))) %>% 
lm_ = lm(data= df_lm , value.x ~ PCE + DFF + DGS10 +  M2SL + UNRATE + CSUSHPINSA + DCOILWTICO + DFF + DGS30 + DGS20 + DTWEXBGS + T10Y2Y)
lm_aic = MASS::stepAIC(object = lm_,verbose=FALSE) 
summary(lm_aic)

```

```{r}

# Current
predict(lm_aic,
        data.frame(MSPUS=450000,
                   PCE=17000,
                   DGS10=3.76,
                   M2SL=21000,
                   DGS20=4.05,
                   DTWEXBGS=123,
                   T10Y2Y=-0.75
  ),interval="prediction")

# Future
predict(lm_aic,
        data.frame(MSPUS=400000,
                   PCE=17000,
                   DGS10=4.25,
                   M2SL=19000,
                   DGS20=4.05,
                   DTWEXBGS=123,
                   T10Y2Y=-0.75
  ),interval="prediction")
```

# Recession Prediction

```{r }
readRenviron(path = "Renviron.site")
fredr::fredr_set_key(key = Sys.getenv("FRED_API"))
```


```{r }
dates = data.frame(date=seq.Date(from = ymd("1960-01-01"),to = ymd("2022-02-01"),by="1 day"))
```

```{r}
recession_bool = fredr::fredr("USREC") %>% 
  filter(value==1) %>% 
  dplyr::select(date) %>% 
  dplyr::mutate(Recession=factor("Yes",levels=c("No","Yes")))
```


## Recession Next 6 Months

```{r}
# Skeleton
recession_next_six_months = fredr::fredr("USREC") %>% 
  filter(value==1) %>% 
  dplyr::select(date) %>% 
  dplyr::mutate(minus1mo=date-months(1),
                minus2mo=date-months(2),
                minus3mo=date-months(3),
                minus4mo=date-months(4),
                minus5mo=date-months(5),
                minus6mo=date-months(6)) %>% 
  gather(date_type,date_val,minus1mo:minus6mo) %>% 
  dplyr::mutate(Recession=factor("Yes",levels=c("No","Yes"))) %>% 
  dplyr::select(date_val,Recession) %>% 
  distinct()
recession_next_six_months = dates %>% 
  left_join(recession_next_six_months,by=c("date"="date_val")) %>% 
  dplyr::mutate(Recession=replace_na(Recession,"No"))

# Data frame with predictors
df_yieldcurve = 
  fredr(series_id = "DGS1") %>% 
  bind_rows(fredr(series_id = "DGS2")) %>% 
  bind_rows(fredr(series_id = "DGS3")) %>% 
  bind_rows(fredr(series_id = "DGS5")) %>% 
  bind_rows(fredr(series_id = "DGS7")) %>% 
  bind_rows(fredr(series_id = "DGS10")) %>% 
  bind_rows(fredr(series_id = "DGS20")) %>% 
  bind_rows(fredr(series_id = "DGS30")) %>% 
  bind_rows(fredr(series_id = "DGS1MO")) %>% 
  bind_rows(fredr(series_id = "DGS3MO")) %>% 
  bind_rows(fredr(series_id = "DGS6MO")) %>% 
  bind_rows(fredr(series_id = "DFF")) %>% 
  bind_rows(fredr(series_id = "MORTGAGE30US")) %>% 
  dplyr::select(-realtime_start,
                -realtime_end)

df_checkboard = expand.grid(date=seq.Date(from = min(df_yieldcurve$date),to = ymd("2022-02-01"),by="1 day"),
                            series_id=unique(df_yieldcurve$series_id),
                            joined_series=unique(df_yieldcurve$series_id))

df_yieldcurve_predictors = df_checkboard %>% 
  left_join(df_yieldcurve) %>% 
  left_join(df_yieldcurve,by=c("joined_series"="series_id","date"="date")) %>% 
  filter(series_id != joined_series) %>% 
  tidyr::fill(value.x,.direction="updown") %>% 
  tidyr::fill(value.y,.direction="updown") %>% 
  dplyr::mutate(spread=value.x-value.y) %>% 
  dplyr::select(series_id,joined_series,date,spread) %>% 
  unite(series_id,series_id,joined_series) %>% 
  spread(series_id,spread)

# Joined
df_fit_recession6mos =
  df_yieldcurve_predictors %>% 
  inner_join(recession_next_six_months)

# Split
df.training = df_fit_recession6mos %>% filter(date<ymd("2018-01-01"))
df.test = df_fit_recession6mos %>% filter(date>ymd("2018-01-01"))

df.training.na_omit = na.omit( df_fit_recession6mos %>% filter(date<ymd("2018-01-01")) )
df.test.na_omit = na.omit( df_fit_recession6mos %>% filter(date>ymd("2018-01-01")) )
```


```{r}
# Control object
trcontrol = caret::trainControl(method = "repeatedcv",
                                number=5,
                                repeats=3,
                                summaryFunction = twoClassSummary,
                                classProbs = TRUE,
                                verboseIter=TRUE)
```


```{r}
# RPART
fit.rpart = caret::train(x = df.training.na_omit %>% dplyr::select(-Recession,-date),
                         y = df.training.na_omit$Recession,
                         metric="ROC",
                         method="rpart",
                         trControl=trcontrol,
                         tuneLength=20)
fit.rpart
plot(as.party(fit.rpart$finalModel))
```


```{r }
# GLM 
fit.glm = glm(Recession~.,
                  data = df_fit_recession6mos %>% dplyr::select(-date) %>% na.omit(),
                  family="binomial")
summary( fit.glm )
```


```{r }
# RANDOM FOREST
fit.rf = caret::train(x = df.training.na_omit %>% dplyr::select(-Recession,-date),
                         y = df.training.na_omit$Recession,
                         metric="ROC",
                         ntree=100,
                         method="rf",
                         tuneGrid=data.frame(mtry=c(1,2,5)),
                         trControl=trcontrol)
fit.rf
varImp(fit.rf)
```


```{r }
# RANDOM FOREST
fit.xgBoost = caret::train(x = df.training.na_omit %>% dplyr::select(-Recession,-date),
                         y = df.training.na_omit$Recession,
                         metric="ROC",
                         method="xgbTree",
                         # tuneGrid=data.frame(mtry=c(1,2,5)),
                         trControl=trcontrol)
fit.xgBoost
varImp(fit.rf)
```

```{r}
# Validate
pred_rpart = predict(fit.rpart,df.test,type = "prob")[,2]
pred_glm = predict(fit.glm,df.test,type = "response")
pred_rf = predict(fit.rf,df.test,type = "prob")[,2]
pred_xgbtree = predict(fit.xgBoost,df.test,type = "prob")[,2]

roc_rpart = pROC::roc(predictor = pred_rpart,response = df.test$Recession)
roc_glm = pROC::roc(predictor = pred_glm,response = df.test$Recession)
roc_rf = pROC::roc(predictor = pred_rf,response = df.test$Recession)
roc_xgbtree = pROC::roc(predictor = pred_xgbtree,response = df.test$Recession)
```


```{r}
plot(roc_xgbtree)
```

```{r}
plot(roc_glm)
```


```{r}
cicoords_glm = ci.coords(roc_glm,x="best",best.method="youden",best.policy="random")
cicoords_cutoff = cicoords_glm$threshold[2]
```

## Extrapolate

```{r}

df.extrapolate = df.test
df.extrapolate$risk = predict(fit.xgBoost,df.extrapolate,type = "prob") %>% pull(Yes) 
df.extrapolate$risk_rf = predict(fit.rf,df.extrapolate,type = "prob") %>% pull(Yes) 

ggplot(df.extrapolate,aes(x=date,y=risk)) +
  geom_line() +
  scale_y_continuous(labels=scales::percent) +
  geom_hline(yintercept = cicoords_cutoff,linetype=2)
```


## Backtest

```{r}

df.backtest = df.training %>% 
  dplyr::mutate(type="Training") %>% 
  bind_rows(df.test) %>% 
  dplyr::mutate(type=tidyr::replace_na(type,"Test"))
df.backtest$risk = predict(fit.xgBoost,df.backtest,type = "prob") %>% pull(Yes) 

ggplot(df.backtest,aes(x=date,y=risk)) +
  geom_line(aes(color=type)) +
  scale_y_continuous(labels=scales::percent,limits=c(0,0.02)) +
  scale_x_date(date_breaks = "3 years",date_labels = "%Y",limits=c(ymd("1980-01-01",NA))) +
  geom_hline(yintercept = cicoords_cutoff,linetype=2) +
  theme_bw() +
  theme(legend.position="bottom")

```



