---
title: "Obligationsrenter"
author: "CAKU"
date: "`r Sys.Date()`"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
```

# Denmark Mortgage Bonds

```{r}

if (!require(pacman)) { install.packages("pacman") }
library(pacman)
pacman::p_load(openxlsx,dplyr,tidyr,ggplot2,lubridate,rvest,zoo,PlayerRatings,fredr)
source(file = "money_theme.R")
```

```{r}
fit_draw_abline = function(date1,date2,value1,value2) {
  
  data.frame(Date=c(date1,date2),
             val=c(value1,value2)) %>% 
    lm(data = .,formula = val~Date) %>% 
    coef(.) %>% 
    as.numeric(.) %>% 
    geom_abline(intercept = .[1],slope = .[2])
  
}
```

```{r}

source_url = "https://finansdanmark.dk/tal-og-data/boligstatistik/obligationsrenter/"
current_url = xml2::read_html(source_url) %>%
  html_node("#wrapper > div > div.sectionB > div.container > div > div.span8 > p:nth-child(10) > a") %>% 
  rvest::html_attr("href")
xlsx_url = paste0("https://finansdanmark.dk/",current_url)

```

```{r}

df_interest = openxlsx::read.xlsx(xlsxFile = xlsx_url,startRow = 3)

df_interest$Date = as.Date(paste(df_interest$År, df_interest$Uge, 1, sep="-"), "%Y-%U-%u")
df_interest = df_interest %>% 
  dplyr::select(Date,Kort.rente,Lang.rente) %>% 
  dplyr::mutate( CurveLongShort = Lang.rente - Kort.rente )

max_date = max(df_interest$Date,na.rm = T)
```

## Short, Long + Spread

```{r}

df_interest %>% 
  gather(stat,val,Kort.rente:Lang.rente) %>% 
  dplyr::mutate(stat=recode(stat,"Kort.rente"="Short","Lang.rente"="30yr","CurveLongShort"="Spread")) %>% 
  dplyr::mutate(val=val/100) %>% 
  ggplot(.,aes(x=Date,y=val,color=stat)) +
  geom_line() +
  scale_x_date(date_breaks = "2 years",date_labels = "%Y") +
  scale_y_continuous(labels = scales::percent,breaks = seq(-0.03,0.1,by=0.005)) +
  # geom_vline(data=data.frame(Date=c(ymd("2005-08-05"),ymd("2005-09-15"),ymd("2021-04-05"),ymd("2021-06-14"))),aes(xintercept=Date)) + 
  geom_hline(yintercept = 0,linetype=2) +
  theme_money_printer_go_brrr(base_size=12) +
  labs(title="Danish Long and Short Interest Rate",
       subtitle=paste0("Source: ",source_url),
       x="Date",
       y="(%)",
       caption = paste0("Data from ",format(max_date,"%Y %b %d"),". ",timestamp_caption())) +
  geom_vline(xintercept = max_date)

```


### Previous 12 Months

```{r}

df_interest %>% 
  filter(Date>=Sys.Date()-years(1)) %>%  
  gather(stat,val,Kort.rente:CurveLongShort) %>% 
  dplyr::mutate(stat=recode(stat,"Kort.rente"="Short","Lang.rente"="30yr","CurveLongShort"="Spread")) %>% 
  dplyr::mutate(val=val/100) %>% 
  ggplot(.,aes(x=Date,y=val,color=stat)) +
  geom_line() +
  scale_x_date(date_breaks = "1 month",date_labels = "%b") +
  scale_y_continuous(labels = scales::percent,breaks = seq(-0.03,0.1,by=0.0025)) +
  geom_hline(yintercept = 0,linetype=2) +
  theme_money_printer_go_brrr(base_size=12) +
  labs(title="Danish Long and Short Interest Rate",
       subtitle=paste0("Source: ",source_url),
       x="Date",
       y="(%)",
       caption = paste0("Data from ",format(max_date,"%Y %b %d"),". ",timestamp_caption())) +
  geom_vline(xintercept = max_date)
```

### Spread

```{r}

df_interest %>% 
  gather(stat,val,CurveLongShort) %>% 
  dplyr::mutate(stat=recode(stat,"Kort.rente"="Short","Lang.rente"="30yr","CurveLongShort"="Spread")) %>% 
  dplyr::mutate(val=val/100) %>% 
  ggplot(.,aes(x=Date,y=val,color=stat)) +
  geom_line() +
  scale_x_date(date_breaks = "1 years",date_labels = "%Y") +
  scale_y_continuous(labels = scales::percent,breaks = seq(-0.03,0.1,by=0.005)) +
  # geom_vline(data=data.frame(Date=c(ymd("2005-08-05"),ymd("2005-09-15"),ymd("2021-04-05"),ymd("2021-06-14"))),aes(xintercept=Date)) + 
  # geom_hline(yintercept = 0,linetype=2) +
  geom_hline(yintercept = 0.035,color="red") +
  fit_draw_abline(date1 = ymd("2021-01-01"),date2 = ymd("2022-05-21"),value1 = 0.015,value2 = 0.0255) +
  theme_money_printer_go_brrr(base_size=12) +
  labs(title="Spread: Danish Long and Short Interest Rate",
       subtitle=paste0("Source: ",source_url),
       x="Date",
       y="(%)",
       caption = paste0("Data from ",format(max_date,"%Y %b %d"),". ",timestamp_caption()))

```



### Short w/ ECB Rate Changes

```{r}

df_interest %>% 
  dplyr::mutate(Kort.rente=Kort.rente/100) %>% 
  ggplot(.,aes(x=Date,y=Kort.rente)) +
  geom_line() +
  scale_y_continuous(limits=c(-0.01,NA),breaks = seq(-0.01,0.07,by=0.005),labels = scales::percent) +
  geom_vline(xintercept = dmy("01-12-2018")) +
  geom_vline(xintercept = c(dmy("09-11-2011"),
                            dmy("14-12-2011"),
                            dmy("11-07-2012"),
                            dmy("13-11-2013"),
                            dmy("08-05-2013"),
                            dmy("11-06-2014"),
                            dmy("10-09-2014"),
                            dmy("09-12-2015"),
                            dmy("16-03-2016"),
                            dmy("18-09-2019")),color="blue",linetype=2) +
  geom_vline(xintercept = c(dmy("13-04-2011"),
                            dmy("13-07-2011")),color="red",linetype=2) + 
  geom_hline(yintercept = 0,linetype=2) +
  theme_money_printer_go_brrr(base_size=12) +
  labs(title="Short Yield",
       x="Date",
       y="Spread (%)",
       caption = timestamp_caption())

```

## Parabolic Support and Resistance

```{r }

lm_low = data.frame(Date=c(ymd("2013-01-01","2015-01-01","2021-01-01")),
           Lang.Rente=c(3.0,2.0,0.91)) %>% 
  lm(log(Lang.Rente)~Date,data=.)

lm_high = data.frame(Date=c(ymd("2011-04-01","2015-07-01")),
           Lang.Rente=c(5.3,3.4)) %>% 
  lm(log(Lang.Rente)~Date,data=.)

df_interest %>% 
  filter(Date>=ymd("2010-01-01")) %>%  
  dplyr::mutate(Lang.rente=Lang.rente/100) %>% 
  dplyr::mutate(Pred_High=exp(predict(lm_high,.))/100,
                Pred_Low=exp(predict(lm_low,.))/100) %>% 
  ggplot(.,aes(x=Date,y=Lang.rente)) +
  geom_line() +
  geom_line(aes(y=Pred_High),linetype=2) +
  geom_line(aes(y=Pred_Low),linetype=2) +
  scale_y_continuous(limits=c(0,0.065),breaks = seq(0,0.065,by=0.005),labels = scales::percent) +
  scale_x_date(date_breaks = "1 year",date_labels = "%Y") +
  geom_hline(yintercept = 0,linetype=2) +
  geom_vline(xintercept = dmy("01-12-2018")) +
  geom_vline(xintercept = c(dmy("09-11-2011"),
                            dmy("14-12-2011"),
                            dmy("11-07-2012"),
                            dmy("13-11-2013"),
                            dmy("08-05-2013"),
                            dmy("11-06-2014"),
                            dmy("10-09-2014"),
                            dmy("09-12-2015"),
                            dmy("16-03-2016"),
                            dmy("18-09-2019")),color="blue",linetype=2) +
  geom_vline(xintercept = c(dmy("13-04-2011"),
                            dmy("13-07-2011")),color="red",linetype=2) +
  geom_vline(xintercept = c(dmy("01-02-2017"),
                            dmy("01-10-2017"),
                            dmy("01-12-2018")),color="green",linetype=2) + 
  theme_money_printer_go_brrr(base_size=12) +
  labs(title="All Yields (Last Year)",
       x="Date",
       y="Spread (%)",
       caption = timestamp_caption()) +
  theme_money_printer_go_brrr(base_size=12) +
  labs(title="Exponential Boundaries of 30yr Mortgage Rate (w/ EBC Rate Changes)",
       subtitle=paste0("Source: ",source_url),
       x="Date",
       y="(%)",
       caption = timestamp_caption())

```


## Historic 5-Year Forward Rate Increases

```{r}

df_interest %>% 
  dplyr::select(Date,Kort.rente,Lang.rente) %>% 
  gather(stat,val,Kort.rente:Lang.rente) %>% 
  group_by(stat) %>% 
  # arrange(stat,desc(Date)) %>% 
  arrange(stat,Date) %>% 
  dplyr::mutate(FutureMax=rollmax(val,k = 5*52,fill = NA,align = "left")-val) %>% 
  ggplot(.,aes(x=Date,y=FutureMax,color=stat)) +
  geom_line() +
  scale_x_date(date_breaks = "1 years",date_labels = "%Y") +
  theme_money_printer_go_brrr(base_size=12) +
  labs(title="Future Rate Increases within 5 yrs",
       x="Date",
       y="Spread (%)",
       caption = timestamp_caption())

```


## Lowest Long Yield and Smallest Spread

```{r}

df_interest %>% 
  dplyr::mutate(Lang.rente=Lang.rente/100,
                CurveLongShort=CurveLongShort/100) %>% 
  dplyr::mutate(Time_Ago=as.numeric(Sys.Date()-Date)) %>% 
  ggplot(.,aes(y=Lang.rente,x=CurveLongShort,color=Time_Ago)) +
  geom_point() +
  scale_y_continuous(limits=c(0,NA),breaks = seq(0,0.1,by=0.005),labels = scales::percent) +
  scale_x_continuous(limits=c(0,NA),breaks = seq(0,0.1,by=0.005),labels = scales::percent) + 
  theme_money_printer_go_brrr(base_size=12) +
  labs(title="Lowest Long Yield to Lowest Short-Long Spread",
       y="Mortgage 30YR Yield",
       x="Short-Long Spread",
       caption = timestamp_caption())

```

## Best Time to Go Fixed

```{r}

df_glicko = data.frame(t(combn(df_interest %>% filter(Date>ymd("2001-01-01")) %>% pull(Date),2)))
df_glicko$X1 = as.Date(df_glicko$X1,origin="1970-01-01")
df_glicko$X2 = as.Date(df_glicko$X2,origin="1970-01-01")

df_glicko_ratings = 
  df_glicko %>% 
  inner_join(df_interest,by=c("X1"="Date")) %>% 
  inner_join(df_interest,by=c("X2"="Date")) %>% 
  dplyr::mutate(Score1=ifelse(Lang.rente.x<Lang.rente.y,1,ifelse(Lang.rente.x>Lang.rente.y,-1,0))) %>% 
  dplyr::mutate(Score2=ifelse(CurveLongShort.x<CurveLongShort.y,1,ifelse(CurveLongShort.x>CurveLongShort.y,-1,0))) %>% 
  dplyr::mutate(Score=Score1+Score2) %>% 
  dplyr::select(X1,X2,Score) %>% 
  dplyr::mutate(result=ifelse(Score>0,1,
                              ifelse(Score<0,0,0.5))) %>% 
  na.omit() %>% 
  dplyr::mutate(Time=1,
                X1=paste0(X1),
                X2=paste0(X2)) %>% 
  dplyr::select(Time,X1,X2,result) %>% 
  PlayerRatings::glicko(.)  %>% 
  .[["ratings"]] %>% 
  dplyr::mutate(Rating=scales::rescale(Rating,to=c(0,100)))

df_glicko_ratings %>% 
  dplyr::mutate(Player=ymd(Player)) %>% 
  ggplot(.,aes(x=Player,y=Rating)) +
  geom_line() +
  scale_y_continuous(limits=c(0,100),breaks = seq(0,100,by=10)) +
  scale_x_date(date_breaks = "1 years",date_labels = "%Y") +
  theme_money_printer_go_brrr(base_size=12) +
  labs(title="Best Time To Go Fixed (0-100)",
       x="Year",
       y="Rating (0-100)",
       caption = timestamp_caption())

```

