---
title: "Predict Interest Rates"
author: "CAKU"
date: "`r Sys.Date()`"
output: html_document
---

```{r  predict_us_interest_rates,include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE,dev = "svg")
```

# Predict US Interest Rates

```{r}
library(pacman)
pacman::p_load(fredr,dplyr,tidyr,lubridate,caret,partykit,pROC,gganimate,devtools,httr,rvest,data.table)
source(file = "money_theme.R")
```

```{r }
readRenviron(path = "Renviron.site")
fredr::fredr_set_key(key = Sys.getenv("FRED_API"))
```

```{r}

add_fomc_meeting_dates = function() {
  geom_vline(xintercept = c(ymd("2022-06-15"),
                            ymd("2022-07-27"),
                            ymd("2022-09-21"),
                            ymd("2022-11-02"),
                            ymd("2022-12-14"),
                            ymd("2023-02-01"),
                            ymd("2023-03-15"),
                            ymd("2023-05-03"),
                            ymd("2023-06-14"),
                            ymd("2023-07-26")),linetype=2,color="#eb493a")
}
```

```{r}
num_trees=1000
tune_grid=data.frame(mtry=c(1,2))
```

```{r}
df_yieldcurve = 
  fredr(series_id = "DGS1") %>% 
  bind_rows(fredr(series_id = "DGS2")) %>% 
  bind_rows(fredr(series_id = "DGS3")) %>% 
  bind_rows(fredr(series_id = "DGS5")) %>% 
  bind_rows(fredr(series_id = "DGS7")) %>% 
  bind_rows(fredr(series_id = "DGS10")) %>% 
  bind_rows(fredr(series_id = "DGS20")) %>% 
  bind_rows(fredr(series_id = "DGS30")) %>% 
  bind_rows(fredr(series_id = "DGS1MO")) %>% 
  bind_rows(fredr(series_id = "DGS3MO")) %>% 
  bind_rows(fredr(series_id = "DGS6MO")) %>% 
  bind_rows(fredr(series_id = "DFF")) %>% 
  bind_rows(fredr(series_id = "MORTGAGE30US"))

order_ = c("DFF",
                                                    "DGS1MO",
                                                    "DGS3MO",
                                                    "DGS6MO",
                                                    "DGS1",
                                                    "DGS2",
                                                    "DGS3",
                                                    "DGS5",
                                                    "DGS7",
                                                    "DGS10",
                                                    "DGS20",
                                                    "DGS30",
                                                    "MORTGAGE30US")
df_yieldcurve = 
  df_yieldcurve %>% 
  dplyr::select(date,series_id,value) %>% 
  dplyr::mutate(series_id=factor(series_id,levels=order_)) %>% 
  spread(series_id,value) %>% 
  arrange(desc(date)) %>% 
  tidyr::fill(c(2:ncol(.)),.direction="up") %>% 
  na.omit() %>% 
  # top_n(n=1,wt=date) %>% 
  gather(series_id,value,c(2:ncol(.))) %>% 
  ungroup() %>% 
  dplyr::mutate(series_id=factor(series_id,levels=order_)) %>% 
  dplyr::mutate(time=ifelse(series_id=="DFF",0,
                            ifelse(substr(series_id,1,8)=="MORTGAGE",
                                   365*30,
                                   ifelse(substr(series_id,5,6)=="MO",
                                          30*as.integer(substr(series_id,4,4)),
                                          365*as.integer(substr(series_id,4,5)))))) 
```

```{r}

source_url = "https://finansdanmark.dk/tal-og-data/boligstatistik/obligationsrenter/"
current_url = xml2::read_html(source_url) %>%
  html_node("#wrapper > div > div.sectionB > div.container > div > div.span8 > p:nth-child(11) > a") %>% 
  rvest::html_attr("href")
xlsx_url = paste0("https://finansdanmark.dk/",current_url)

df_DK = openxlsx::read.xlsx(xlsxFile = xlsx_url,startRow = 3)

df_DK$date = as.Date(paste(df_DK$År, df_DK$Uge, 1, sep="-"), "%Y-%U-%u")
df_DK = df_DK %>% 
  dplyr::select(date,Kort.rente,Lang.rente) %>% 
  rename(DK_Short=Kort.rente,
         DK_Long=Lang.rente) %>% 
  dplyr::mutate( DK_Spread = DK_Short - DK_Long ) %>% 
  gather(series_id,value,DK_Short:DK_Spread)
```

```{r}
df_INFLATION = 
  fredr(series_id = "CPIAUCSL") %>% 
  arrange(date) %>% 
  dplyr::mutate(value=100*((value/lag(x = value,n = 12))-1))

```


```{r}

df_checkboard = expand.grid(series_id=unique(df_yieldcurve$series_id),
                            joined_series=unique(df_yieldcurve$series_id))

df_yield_checkboard = 
  df_checkboard %>% 
  inner_join(df_yieldcurve) %>% 
  inner_join(df_yieldcurve,by=c("joined_series"="series_id","date"="date")) %>% 
  dplyr::mutate(spread=value.x-value.y) %>% 
  dplyr::mutate(label=ifelse(spread<0,spread,NA)) %>% 
  dplyr::select(series_id,joined_series,date,spread,label) %>% 
  dplyr::mutate(series_id=factor(series_id,levels=order_),
                joined_series=factor(joined_series,levels=order_))

```


```{r}

train_control = caret::trainControl(method = "repeatedcv",number = 5,repeats = 5)

```

```{r}
df_DFF = 
  df_yieldcurve %>% 
  filter(series_id=="DFF") %>% 
  dplyr::select(date,value)

df_DGS2 = 
  df_yieldcurve %>% 
  filter(series_id=="DGS2") %>% 
  dplyr::select(date,value)

df_DGS10 = 
  df_yieldcurve %>% 
  filter(series_id=="DGS10") %>% 
  dplyr::select(date,value)

df_DGS30 = 
  df_yieldcurve %>% 
  filter(series_id=="DGS30") %>% 
  dplyr::select(date,value)

df_MORTGAGE30US = 
  df_yieldcurve %>% 
  filter(series_id=="MORTGAGE30US") %>% 
  dplyr::select(date,value)

df_MORTGAGE30US = 
  df_yieldcurve %>% 
  filter(series_id=="MORTGAGE30US") %>% 
  dplyr::select(date,value)

df_DK_Short =
  df_DK %>% 
  filter(series_id=="DK_Short") %>% 
  dplyr::select(date,value) %>% 
  tidyr::complete(date=seq.Date(from=min(date,na.rm=T),to=max(date,na.rm=T),by="1 day")) %>% 
  tidyr::fill(value,.direction = "down")

df_DK_Long = 
  df_DK %>% 
  filter(series_id=="DK_Long") %>% 
  dplyr::select(date,value) %>% 
  tidyr::complete(date=seq.Date(from=min(date,na.rm=T),to=max(date,na.rm=T),by="1 day")) %>% 
  tidyr::fill(value,.direction = "down")

df_CPIAUCSL = 
  df_INFLATION %>% 
  filter(series_id=="CPIAUCSL") %>% 
  dplyr::select(date,value) %>% 
  tidyr::complete(date=seq.Date(from=min(date,na.rm=T),to=max(date,na.rm=T),by="1 day")) %>% 
  tidyr::fill(value,.direction = "down")



```


```{r}

df_predict_DFF = df_yield_checkboard %>% 
  filter(series_id!=joined_series) %>% 
  dplyr::mutate(one_year_ahead=date+years(1)) %>% 
  left_join(df_DFF,by=c("one_year_ahead"="date")) %>% 
  unite(series_id,series_id,joined_series) %>% 
  dplyr::select(date,series_id,spread,value) %>% 
  spread(series_id,spread)

df_predict_DGS2 = df_yield_checkboard %>% 
  filter(series_id!=joined_series) %>% 
  dplyr::mutate(one_year_ahead=date+years(1)) %>% 
  left_join(df_DGS2,by=c("one_year_ahead"="date")) %>% 
  unite(series_id,series_id,joined_series) %>% 
  dplyr::select(date,series_id,spread,value) %>% 
  spread(series_id,spread)

df_predict_DGS10 = df_yield_checkboard %>% 
  filter(series_id!=joined_series) %>% 
  dplyr::mutate(one_year_ahead=date+years(1)) %>% 
  left_join(df_DGS10,by=c("one_year_ahead"="date")) %>% 
  unite(series_id,series_id,joined_series) %>% 
  dplyr::select(date,series_id,spread,value) %>% 
  spread(series_id,spread)

df_predict_DGS30 = df_yield_checkboard %>% 
  filter(series_id!=joined_series) %>% 
  dplyr::mutate(one_year_ahead=date+years(1)) %>% 
  left_join(df_DGS30,by=c("one_year_ahead"="date")) %>% 
  unite(series_id,series_id,joined_series) %>% 
  dplyr::select(date,series_id,spread,value) %>% 
  spread(series_id,spread)

df_predict_MORTGAGE30US = df_yield_checkboard %>% 
  filter(series_id!=joined_series) %>% 
  dplyr::mutate(one_year_ahead=date+years(1)) %>% 
  left_join(df_MORTGAGE30US,by=c("one_year_ahead"="date")) %>% 
  unite(series_id,series_id,joined_series) %>% 
  dplyr::select(date,series_id,spread,value) %>% 
  spread(series_id,spread)

df_predict_DK_Short = df_yield_checkboard %>% 
  filter(series_id!=joined_series) %>% 
  dplyr::mutate(one_year_ahead=date+years(1)) %>% 
  left_join(df_DK_Short,by=c("one_year_ahead"="date")) %>% 
  unite(series_id,series_id,joined_series) %>% 
  dplyr::select(date,series_id,spread,value) %>% 
  spread(series_id,spread) 

df_predict_DK_Long = df_yield_checkboard %>% 
  filter(series_id!=joined_series) %>% 
  dplyr::mutate(one_year_ahead=date+years(1)) %>% 
  left_join(df_DK_Long,by=c("one_year_ahead"="date")) %>% 
  unite(series_id,series_id,joined_series) %>% 
  dplyr::select(date,series_id,spread,value) %>% 
  spread(series_id,spread) %>% 
  arrange(desc(date))

df_predict_DK_Long = df_yield_checkboard %>% 
  filter(series_id!=joined_series) %>% 
  dplyr::mutate(one_year_ahead=date+years(1)) %>% 
  left_join(df_DK_Long,by=c("one_year_ahead"="date")) %>% 
  unite(series_id,series_id,joined_series) %>% 
  dplyr::select(date,series_id,spread,value) %>% 
  spread(series_id,spread) %>% 
  arrange(desc(date))

df_predict_CPIAUCSL = df_yield_checkboard %>% 
  filter(series_id!=joined_series) %>% 
  dplyr::mutate(one_year_ahead=date+years(1)) %>% 
  left_join(df_CPIAUCSL,by=c("one_year_ahead"="date")) %>% 
  unite(series_id,series_id,joined_series) %>% 
  dplyr::select(date,series_id,spread,value) %>% 
  spread(series_id,spread) %>% 
  arrange(desc(date))



```


```{r}


tune_grid=data.frame(mtry=c(5))

fit_DFF = caret::train(x = df_predict_DFF %>% 
                              na.omit %>% 
                              dplyr::select(-date,-value) %>% 
                              data.frame(),
                         y = df_predict_DFF %>% 
                           na.omit %>% 
                           .[["value"]],
                         method = "rf",
                         tuneGrid=tune_grid,
                         ntree=num_trees,
                         metric = "RMSE",
                         trControl=train_control)

fit_DGS2 = caret::train(x = df_predict_DGS2 %>% 
                              na.omit %>% 
                              dplyr::select(-date,-value) %>% 
                              data.frame(),
                         y = df_predict_DGS2 %>% 
                           na.omit %>% 
                           .[["value"]],
                         method = "rf",
                         tuneGrid=tune_grid,
                         ntree=num_trees,
                         metric = "RMSE",
                         trControl=train_control)
fit_DGS10= caret::train(x = df_predict_DGS10 %>% 
                              na.omit %>% 
                              dplyr::select(-date,-value) %>% 
                              data.frame(),
                         y = df_predict_DGS10 %>% 
                           na.omit %>% 
                           .[["value"]],
                         method = "rf",
                         tuneGrid=tune_grid,
                         ntree=num_trees,
                         metric = "RMSE",
                         trControl=train_control)
fit_DGS30 = caret::train(x = df_predict_DGS30 %>% 
                              na.omit %>% 
                              dplyr::select(-date,-value) %>% 
                              data.frame(),
                         y = df_predict_DGS30 %>% 
                           na.omit %>% 
                           .[["value"]],
                         method = "rf",
                         tuneGrid=tune_grid,
                         ntree=num_trees,
                         metric = "RMSE",
                         trControl=train_control)
fit_MORTGAGE30US = caret::train(x = df_predict_MORTGAGE30US %>% 
                              na.omit %>% 
                              dplyr::select(-date,-value) %>% 
                              data.frame(),
                         y = df_predict_MORTGAGE30US %>% 
                           na.omit %>% 
                           .[["value"]],
                         method = "rf",
                         tuneGrid=tune_grid,
                         ntree=num_trees,
                         metric = "RMSE",
                         trControl=train_control)
fit_DK_Short = caret::train(x = df_predict_DK_Short %>% 
                              na.omit %>% 
                              dplyr::select(-date,-value) %>% 
                              data.frame(),
                         y = df_predict_DK_Short %>% 
                           na.omit %>% 
                           .[["value"]],
                         method = "rf",
                         tuneGrid=tune_grid,
                         ntree=num_trees,
                         metric = "RMSE",
                         trControl=train_control)
fit_DK_Long = caret::train(x = df_predict_DK_Long %>% 
                              na.omit %>% 
                              dplyr::select(-date,-value) %>% 
                              data.frame(),
                         y = df_predict_DK_Long %>% 
                           na.omit %>% 
                           .[["value"]],
                         method = "rf",
                         tuneGrid=tune_grid,
                         ntree=num_trees,
                         metric = "RMSE",
                         trControl=train_control)
fit_CPIAUCSL = caret::train(x = df_predict_CPIAUCSL %>% 
                              na.omit %>% 
                              dplyr::select(-date,-value) %>% 
                              data.frame(),
                         y = df_predict_CPIAUCSL %>% 
                           na.omit %>% 
                           .[["value"]],
                         method = "rf",
                         tuneGrid=tune_grid,
                         ntree=num_trees,
                         metric = "RMSE",
                         trControl=train_control)
```


## Predicted US Yield

```{r fig.width=15,fig.height=15}

df_predict_DFF %>% 
  dplyr::mutate(pred_DFF=predict(fit_DFF,.)) %>% 
  dplyr::select(date,pred_DFF) %>% 
  dplyr::mutate(date=date+years(1)) %>%
  gather(pred,val,pred_DFF) %>%
  crossing(one_year=c(TRUE,FALSE)) %>% 
  dplyr::mutate(date=ifelse(one_year,
                            ifelse(date>=Sys.Date()-years(1),date,NA),date)) %>% 
  filter(!is.na(date)) %>% 
  dplyr::mutate(date=as.Date(date,origin="1970-01-01")) %>%
  filter(!one_year) %>% 
  ggplot(.,aes(x=date,y=val,color=pred)) +
  geom_line(size=1) +
  scale_x_date(date_breaks = "1 year",date_labels = "%Y") +
  scale_y_continuous(breaks = seq(0,10,0.5)) +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  geom_vline(xintercept = Sys.Date(),linetype=2) +
  geom_hline(yintercept = 0,linetype=2) +
  # facet_wrap(~one_year,scales="free",ncol=1) +
  theme_money_printer_go_brrr(base_size=20) +
  labs(title="Predicted/Observed T-Bond Yields",
       x=NULL,
       y="(%)",
       caption = timestamp_caption())
           

```

```{r fig.width=15,fig.height=15}

df_predict_DFF %>% 
  dplyr::mutate(pred_DFF=predict(fit_DFF,.),
                pred_DGS2=predict(fit_DGS2,.),
                pred_DGS10=predict(fit_DGS10,.),
                pred_DGS30=predict(fit_DGS30,.),
                pred_MORTGAGE30US=predict(fit_MORTGAGE30US,.)) %>% 
  dplyr::select(date,pred_DFF:pred_MORTGAGE30US) %>% 
  dplyr::mutate(date=date+years(1)) %>%
  gather(pred,val,pred_DFF:pred_MORTGAGE30US) %>%
  crossing(one_year=c(TRUE,FALSE)) %>% 
  dplyr::mutate(date=ifelse(one_year,
                            ifelse(date>=Sys.Date()-years(1),date,NA),date)) %>% 
  filter(!is.na(date)) %>% 
  dplyr::mutate(date=as.Date(date,origin="1970-01-01")) %>%
  filter(!one_year) %>% 
  ggplot(.,aes(x=date,y=val,color=pred)) +
  geom_line(size=1) +
  scale_x_date(date_breaks = "1 year",date_labels = "%Y") +
  scale_y_continuous(breaks = seq(0,10,0.5)) +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  geom_vline(xintercept = Sys.Date(),linetype=2) +
  geom_hline(yintercept = 0,linetype=2) +
  # facet_wrap(~one_year,scales="free",ncol=1) +
  theme_money_printer_go_brrr(base_size=20) +
  labs(title="Predicted/Observed T-Bond Yields",
       x=NULL,
       y="(%)",
       caption = timestamp_caption())
                
```

```{r fig.width=15,fig.height=15}

df_predict_DFF %>% 
  dplyr::mutate(pred_DFF=predict(fit_DFF,.),
                pred_DGS2=predict(fit_DGS2,.),
                pred_DGS10=predict(fit_DGS10,.),
                pred_DGS30=predict(fit_DGS30,.),
                pred_MORTGAGE30US=predict(fit_MORTGAGE30US,.)) %>% 
  dplyr::select(date,pred_DFF:pred_MORTGAGE30US) %>% 
  dplyr::mutate(date=date+years(1)) %>%
  gather(pred,val,pred_DFF:pred_MORTGAGE30US) %>%
  crossing(one_year=c(TRUE,FALSE)) %>% 
  dplyr::mutate(date=ifelse(one_year,
                            ifelse(date>=Sys.Date()-years(1),date,NA),date)) %>% 
  filter(!is.na(date)) %>% 
  dplyr::mutate(date=as.Date(date,origin="1970-01-01")) %>%
  filter(one_year) %>% 
  ggplot(.,aes(x=date,y=val,color=pred)) +
  geom_line(size=1) +
  scale_x_date(date_breaks = "1 month",date_labels = "%b") +
  scale_y_continuous(breaks = seq(0,10,0.5)) +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  geom_vline(xintercept = Sys.Date(),linetype=2) +
  geom_hline(yintercept = 0,linetype=2) +
  # facet_wrap(~one_year,scales="free",ncol=1) +
  theme_money_printer_go_brrr(base_size=20) +
  labs(title="Predicted/Observed T-Bond Yields",
       x=NULL,
       y="(%)",
       caption = timestamp_caption()) +
  add_fomc_meeting_dates()
                
```

## Future Yield Curves

```{r fig.width=15,fig.height=15}

df_predict_DFF %>% 
  dplyr::mutate(pred_DFF=predict(fit_DFF,.),
                pred_DGS2=predict(fit_DGS2,.),
                pred_DGS10=predict(fit_DGS10,.),
                pred_DGS30=predict(fit_DGS30,.),
                pred_MORTGAGE30US=predict(fit_MORTGAGE30US,.)) %>% 
  dplyr::select(date,pred_DFF:pred_MORTGAGE30US) %>% 
  dplyr::mutate(date=date+years(1)) %>%
  filter(date>=Sys.Date()) %>% 
  filter(date %in% unique(date)[seq(1,length(date),length.out=6)]) %>%
  gather(pred,val,pred_DFF:pred_MORTGAGE30US) %>% 
  dplyr::mutate(pred=factor(pred,levels=c("pred_DFF",
                                          "pred_DGS2",
                                          "pred_DGS10",
                                          "pred_DGS30",
                                          "pred_MORTGAGE30US"))) %>% 
  ggplot(.,aes(x=pred,y=val,color=factor(date),group=date)) +
  geom_line(size=1) +
  scale_y_continuous(breaks = seq(0,10,0.5)) +
  theme_money_printer_go_brrr(base_size=20) +
  labs(title="Predicted Yield Curves",
       x=NULL,
       y="(%)",
       caption = timestamp_caption())
                
```

## Future FED FOMC Meeting Rate changes

```{r fig.width=15,fig.height=15}

fomc_dates = data.frame(date_fomc=c(ymd("2022-05-04"),
               ymd("2022-06-15"),
               ymd("2022-07-27"),
               ymd("2022-09-21"),
               ymd("2022-11-02"),
               ymd("2022-12-14"),
               ymd("2023-02-01"),
               Sys.Date())) %>% 
  filter(date_fomc>=Sys.Date())


df_predict_DFF %>% 
  dplyr::mutate(pred_DFF=predict(fit_DFF,.),
                pred_DGS2=predict(fit_DGS2,.),
                pred_DGS10=predict(fit_DGS10,.),
                pred_DGS30=predict(fit_DGS30,.),
                pred_MORTGAGE30US=predict(fit_MORTGAGE30US,.)) %>% 
  dplyr::select(date,pred_DFF:pred_MORTGAGE30US) %>% 
  dplyr::mutate(date=date+years(1)) %>%
  gather(pred,val,pred_DFF:pred_MORTGAGE30US) %>%
  filter(!is.na(date)) %>% 
  dplyr::mutate(date=as.Date(date,origin="1970-01-01")) %>% 
  tidyr::crossing(fomc_dates) %>% 
  group_by( date_fomc ) %>% 
  filter(date-date_fomc>=0) %>% 
  filter(date-date_fomc==min(date-date_fomc)) %>% 
  filter(pred=="pred_DFF") %>% 
  dplyr::mutate(val=ceiling(val/0.25)*0.25/100) %>% 
  ggplot(.,aes(x=date_fomc,y=val)) +
  geom_point(size=3) + 
  geom_line(size=1) +
  scale_y_continuous(breaks = seq(0,0.1,by=0.0025),labels = scales::percent,limits = c(0,NA)) +
  scale_x_date(date_breaks = "1 month",date_labels = "%b") +
  geom_vline(data=fomc_dates,aes(xintercept=date_fomc),linetype=2) +
  theme_money_printer_go_brrr(base_size=20) +
  labs(title="Predicted FOMC Meeting Rates",
       x=NULL,
       y="(%)",
       caption = timestamp_caption())

                
```



```{r fig.width=15,fig.height=15}

fit_DFF_previous = rbindlist(lapply(c(7,30,180,365),function(days_ago) {
  
  temp_df =df_predict_DFF %>% 
    filter(date<=Sys.Date()-days(days_ago))
  
  temp_fit = caret::train(x = temp_df %>% 
                              na.omit %>% 
                              dplyr::select(-date,-value) %>% 
                              data.frame(),
                         y = temp_df %>% 
                           na.omit %>% 
                           .[["value"]],
                         method = "rf",
                         tuneGrid=tune_grid,
                         ntree=num_trees,
                         metric = "RMSE",
                         trControl=train_control)
  
  temp_df %>% 
    dplyr::mutate(pred_DFF=predict(temp_fit,.)) %>% 
    dplyr::select(date,pred_DFF) %>% 
    dplyr::mutate(date=date+years(1),
                  days_ago=days_ago,) %>%
    gather(pred,val,pred_DFF) 
  
}))

fit_DFF_previous %>% 
  filter(!is.na(date)) %>% 
  dplyr::mutate(date=as.Date(date,origin="1970-01-01"),
                days_ago=factor(days_ago)) %>% 
  tidyr::crossing(fomc_dates) %>% 
  group_by( date_fomc ) %>% 
  filter(date-date_fomc>=0) %>% 
  filter(date-date_fomc==min(date-date_fomc)) %>% 
  filter(pred=="pred_DFF") %>% 
  dplyr::mutate(val=ceiling(val/0.25)*0.25/100) %>% 
  ggplot(.,aes(x=date_fomc,y=val,color=days_ago)) +
  geom_point() + 
  geom_line() +
  scale_y_continuous(breaks = seq(0,0.1,by=0.0025),labels = scales::percent,limits = c(0,NA)) +
  scale_x_date(date_breaks = "1 month",date_labels = "%b") +
  geom_vline(data=fomc_dates,aes(xintercept=date_fomc),linetype=2) +
  theme_money_printer_go_brrr(base_size=12) +
  labs(title="Predicted FOMC Meeting Rates",
       x=NULL,
       y="(%)",
       caption = timestamp_caption())


```


## Danish Short and Long

```{r fig.width=15,fig.height=15}

df_predict_DK_Short %>% 
  # filter(date>=Sys.Date()-years(2)) %>% 
  dplyr::mutate(pred_DK_Short=predict(fit_DK_Short,.),
                pred_DK_Long=predict(fit_DK_Long,.)) %>% 
  dplyr::mutate(pred_spread=pred_DK_Long-pred_DK_Short) %>% 
  # dplyr::mutate(pred_glm=predict(lm_DFF,.),
  #               pred_rpart=predict(fit_rpart,.)) %>% 
  dplyr::select(date,pred_DK_Short,pred_DK_Long,pred_spread,value) %>%
  # dplyr::select(date,pred_glm,value) %>% 
  dplyr::mutate(date=date+years(1)) %>%
  gather(pred,val,pred_DK_Short:pred_spread) %>%
  tidyr::crossing(one_year=c(TRUE,FALSE)) %>% 
  dplyr::mutate(date=ifelse(one_year,
                            ifelse(date>=Sys.Date()-years(1),date,NA),date)) %>% 
  filter(!is.na(date)) %>% 
  dplyr::mutate(date=as.Date(date,origin="1970-01-01"))  %>%
    filter(!one_year) %>% 
  ggplot(.,aes(x=date,y=val,color=pred)) +
  geom_line() +
  geom_line(data=df_DK_Short %>% 
               dplyr::mutate(pred="Observed") %>%
  tidyr::crossing(one_year=c(TRUE,FALSE)) %>% 
  dplyr::mutate(date=ifelse(one_year,
                            ifelse(date>=Sys.Date()-years(1),date,NA),date)) %>% 
  filter(!is.na(date)) %>% 
  dplyr::mutate(date=as.Date(date,origin="1970-01-01")),aes(x=date,y=value))  +
  geom_line(data=df_DK_Long %>% 
               dplyr::mutate(pred="Observed") %>%
  tidyr::crossing(one_year=c(TRUE,FALSE)) %>% 
  dplyr::mutate(date=ifelse(one_year,
                            ifelse(date>=Sys.Date()-years(1),date,NA),date)) %>% 
  filter(!is.na(date)) %>% 
  dplyr::mutate(date=as.Date(date,origin="1970-01-01")),aes(x=date,y=value))  +
  scale_x_date(date_breaks = "1 year",date_labels = "%Y") +
  scale_y_continuous(breaks = seq(0,10,0.5)) +
  theme(axis.text.x=element_text(angle=45,hjust=1))  +
  geom_vline(xintercept = Sys.Date(),linetype=2) +
  geom_hline(yintercept = 0,linetype=2) +
  theme_money_printer_go_brrr(base_size=20) +
  labs(title="Predicted/Observed Long and Short Interest Rate",
       x=NULL,
       y="(%)",
       caption = timestamp_caption())

```

```{r fig.width=15,fig.height=15}

df_predict_DK_Short %>% 
  # filter(date>=Sys.Date()-years(2)) %>% 
  dplyr::mutate(pred_DK_Short=predict(fit_DK_Short,.),
                pred_DK_Long=predict(fit_DK_Long,.)) %>% 
  dplyr::mutate(pred_spread=pred_DK_Long-pred_DK_Short) %>% 
  # dplyr::mutate(pred_glm=predict(lm_DFF,.),
  #               pred_rpart=predict(fit_rpart,.)) %>% 
  dplyr::select(date,pred_DK_Short,pred_DK_Long,pred_spread,value) %>%
  # dplyr::select(date,pred_glm,value) %>% 
  dplyr::mutate(date=date+years(1)) %>%
  gather(pred,val,pred_DK_Short:pred_spread) %>%
  tidyr::crossing(one_year=c(TRUE,FALSE)) %>% 
  dplyr::mutate(date=ifelse(one_year,
                            ifelse(date>=Sys.Date()-years(1),date,NA),date)) %>% 
  filter(!is.na(date)) %>% 
  dplyr::mutate(date=as.Date(date,origin="1970-01-01"))  %>%
  filter(one_year) %>% 
  ggplot(.,aes(x=date,y=val,color=pred),size=2) +
  geom_line() +
  geom_line(data=df_DK_Short %>% 
               dplyr::mutate(pred="Observed") %>%
  tidyr::crossing(one_year=c(TRUE,FALSE)) %>% 
  dplyr::mutate(date=ifelse(one_year,
                            ifelse(date>=Sys.Date()-years(1),date,NA),date)) %>% 
  filter(!is.na(date)) %>% 
  dplyr::mutate(date=as.Date(date,origin="1970-01-01")),aes(x=date,y=value))  +
  geom_line(data=df_DK_Long %>% 
               dplyr::mutate(pred="Observed") %>%
  tidyr::crossing(one_year=c(TRUE,FALSE)) %>% 
  dplyr::mutate(date=ifelse(one_year,
                            ifelse(date>=Sys.Date()-years(1),date,NA),date)) %>% 
  filter(!is.na(date)) %>% 
  dplyr::mutate(date=as.Date(date,origin="1970-01-01")),aes(x=date,y=value))  +
  scale_x_date(date_breaks = "1 month",date_labels = "%b",limits=c(Sys.Date()-years(1),NA)) +
  scale_y_continuous(breaks = seq(0,10,0.5),limits=c(NA,5)) +
  theme(axis.text.x=element_text(angle=45,hjust=1))  +
  geom_vline(xintercept = Sys.Date(),linetype=2) +
  geom_hline(yintercept = 0,linetype=2) +
  theme_money_printer_go_brrr(base_size=20) +
  labs(title="Predicted/Observed Long and Short Interest Rate",
       x=NULL,
       y="(%)",
       caption = timestamp_caption())

```

## Inflation Expectations

```{r fig.width=15,fig.height=15}

df_predict_CPIAUCSL %>% 
  dplyr::mutate(pred_CPIAUCSL=predict(fit_CPIAUCSL,.)) %>% 
  dplyr::select(date,pred_CPIAUCSL,value) %>% 
  dplyr::mutate(date=date+years(1)) %>%
  gather(pred,val,pred_CPIAUCSL:value) %>%
  crossing(one_year=c(TRUE,FALSE)) %>% 
  dplyr::mutate(date=ifelse(one_year,
                            ifelse(date>=Sys.Date()-years(1),date,NA),date)) %>% 
  filter(!is.na(date)) %>% 
  dplyr::mutate(date=as.Date(date,origin="1970-01-01")) %>%
  filter(one_year) %>% 
  ggplot(.,aes(x=date,y=val,color=pred)) +
  geom_line(size=1) +
  scale_x_date(date_breaks = "1 month",date_labels = "%b") +
  scale_y_continuous(breaks = seq(0,10,0.1)) +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  add_fomc_meeting_dates() +
  geom_vline(xintercept = Sys.Date(),linetype=2) +
  # geom_hline(yintercept = 0,linetype=2) +
  # facet_wrap(~one_year,scales="free",ncol=1) +
  theme_money_printer_go_brrr(base_size=20) +
  labs(title="Predicted/Observed YoY Inflation",
       x=NULL,
       y="(%)",
       caption = timestamp_caption())

```


