---
title: "Denmark: Housing Market Supply"
author: "CAKU"
date: "`r Sys.Date()`"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
options(scipen=999)

```

```{r }
library(pacman)
pacman::p_load(tidyr,dplyr,ggplot2,boot,openxlsx,lubridate,forcats,broom,purrr,caret,glue,devtools,dkstat,zoo)
source(file = "money_theme.R")
```

```{r}
loess_adjust = function(data) {
  
  # grid <- expand.grid(span = seq(0.1, 0.5, len = 5), degree = c(1))
  # fit_gam = suppressWarnings(expr =  { train(y = data$VALUE, 
  #       x = data %>% dplyr::select(DATE),
  #       tuneGrid=grid,
  #       method = "gamLoess") })
  
  
  fit_smooth = smooth.spline(x = data$DATE, 
                             y = data$VALUE, 
                             all.knots = TRUE, 
                             control.spar = list(low = -2, hight = 2))
  
  data %>% 
    dplyr::mutate(VALUE=fit_smooth$y) %>% 
    dplyr::mutate(VALUE=scale(VALUE,center=TRUE,scale=TRUE)) %>%
    dplyr::mutate(ema=TTR::EMA(VALUE,9))
  
}
```

# Denmark Housing Supply


```{r}
df_udbud =
  openxlsx::read.xlsx(xlsxFile = "Data/202236193052365370194UDB010_2.xlsx",startRow = 3) %>% 
  dplyr::rename(SUPPLY_TYPE=X1,
                PROPERTY_TYPE=X2,
                ZIP=X3) %>% 
  tidyr::fill(SUPPLY_TYPE,.direction="down") %>% 
  tidyr::fill(PROPERTY_TYPE,.direction="down") %>% 
  tidyr::fill(ZIP,.direction="down") %>% 
  gather(DATE,VALUE,c(4:ncol(.))) %>% 
  filter(!VALUE=="..") %>% 
  dplyr::mutate(DATE=lubridate::ceiling_date(ymd(glue("{substr(DATE,1,4)}-{substr(DATE,6,7)}-01")),unit="month")-days(1)) %>% 
  group_by(PROPERTY_TYPE,ZIP) %>%
  do(loess_adjust(.))

```

```{r}
df_udbud.change =
  openxlsx::read.xlsx(xlsxFile = "Data/202236193052365370194UDB010_2.xlsx",startRow = 3) %>% 
  dplyr::rename(SUPPLY_TYPE=X1,
                PROPERTY_TYPE=X2,
                ZIP=X3) %>% 
  tidyr::fill(SUPPLY_TYPE,.direction="down") %>% 
  tidyr::fill(PROPERTY_TYPE,.direction="down") %>% 
  tidyr::fill(ZIP,.direction="down") %>% 
  gather(DATE,VALUE,c(4:ncol(.))) %>% 
  filter(!VALUE=="..") %>% 
  dplyr::mutate(DATE=lubridate::ceiling_date(ymd(glue("{substr(DATE,1,4)}-{substr(DATE,6,7)}-01")),unit="month")-days(1)) %>% 
  group_by(PROPERTY_TYPE,ZIP) %>%  
  do(loess_adjust(.)) %>% 
  arrange(PROPERTY_TYPE,ZIP,DATE) %>% 
  dplyr::mutate(next_period_chg=lead(VALUE)-VALUE)
```

```{r}

df_udbud.bubblelow = df_udbud %>% 
  filter(DATE>ymd("2005-01-01")) %>% 
  filter(DATE<ymd("2008-01-01")) %>% 
  group_by(PROPERTY_TYPE,ZIP) %>% 
  filter(VALUE==min(VALUE)) %>% 
  dplyr::select(PROPERTY_TYPE,ZIP,DATE)

df_udbud.bubblelow.DK = 
  df_udbud.bubblelow %>% 
  group_by(PROPERTY_TYPE) %>% 
  dplyr::summarise(DATE=mean(DATE))

```

```{r}

df_udbud.covid19low = df_udbud %>% 
  filter(DATE>ymd("2020-01-01")) %>% 
  group_by(PROPERTY_TYPE,ZIP) %>% 
  filter(VALUE==min(VALUE)) %>% 
  dplyr::select(PROPERTY_TYPE,ZIP,DATE)

df_udbud.covid19low.DK = 
  df_udbud.covid19low %>% 
  group_by(PROPERTY_TYPE) %>% 
  dplyr::summarise(DATE=mean(DATE))

```

```{r}
df.house_prices =
  openxlsx::read.xlsx(xlsxFile = "Data/20223617848365363032BM011_2.xlsx",startRow = 3) %>% 
  setNames(.,c("ZIP","DATE","STAT","HOUSE","FLAT")) %>% 
  tidyr::fill(ZIP,.direction="down") %>% 
  tidyr::fill(DATE,.direction="down") %>% 
  gather(PROPERTY_TYPE,VALUE,HOUSE,FLAT) %>% 
  filter(!VALUE=="..") %>% 
  dplyr::mutate(VALUE=as.integer(VALUE)) %>% 
  dplyr::mutate(DATE=lubridate::ceiling_date(as.Date(as.yearqtr(DATE, format = "%YK%q")),"quarters")-days(1)) %>% 
  group_by(PROPERTY_TYPE,STAT,ZIP) %>% 
  # do(loess_adjust(.)) %>% 
  dplyr::mutate(PROPERTY_TYPE=recode(PROPERTY_TYPE, 'HOUSE'='Parcel-/rækkehuse', 'FLAT'='Ejerlejlighed'))

```

```{r}

df_liggetider =
  openxlsx::read.xlsx(xlsxFile = "Data/202236191752365370194UDB030_2.xlsx",startRow = 3) %>% 
  dplyr::rename(STAT=X1,
                PROPERTY_TYPE=X2,
                ZIP=X3) %>% 
  tidyr::fill(STAT,.direction="down") %>% 
  tidyr::fill(PROPERTY_TYPE,.direction="down") %>% 
  filter(STAT=="Liggetider (dage)") %>% 
  gather(DATE,VALUE,c(4:ncol(.))) %>% 
  filter(!VALUE=="..") %>% 
  group_by(PROPERTY_TYPE,STAT,ZIP) %>% 
  dplyr::mutate(INDEX=scale(VALUE,center = TRUE,scale = TRUE)) %>% 
  dplyr::mutate(DATE=lubridate::ceiling_date(ymd(glue("{substr(DATE,1,4)}-{substr(DATE,6,7)}-01")),unit="month")-days(1))

```


```{r }

BYGV80_meta <- dst_meta(table = "BYGV80", lang = "da")
BYGV80 <- dst_get_data(table = "BYGV80", 
                       BYGFASE="*",
                       ANVENDELSE="*",
                       Tid="*",
                       lang = "da")
df_BYGV80 = 
  BYGV80 %>% 
  group_by(BYGFASE,ANVENDELSE) %>% 
  arrange(BYGFASE,ANVENDELSE,TID) %>% 
  filter(ANVENDELSE %in% c("Etageboliger","Parcelhuse")) %>% 
  dplyr::mutate(ANVENDELSE=gsub("Etageboliger","FLAT",ANVENDELSE)) %>% 
  dplyr::mutate(ANVENDELSE=gsub("Parcelhuse","HOUSE",ANVENDELSE)) %>% 
  dplyr::rename(PROPERTY_TYPE=ANVENDELSE) %>% 
  dplyr::rename(STAT=BYGFASE) %>% 
  dplyr::rename(DATE=TID) %>% 
  dplyr::rename(VALUE=value) %>% 
  group_by(PROPERTY_TYPE,STAT) %>% 
  dplyr::mutate(PROPERTY_TYPE=recode(PROPERTY_TYPE, 'HOUSE'='Parcel-/rækkehuse', 'FLAT'='Ejerlejlighed')) %>% 
  dplyr::mutate(INDEX=scale(VALUE,center = TRUE,scale = TRUE)) %>% 
  na.omit()

```


```{r}

source_url = "https://finansdanmark.dk/tal-og-data/boligstatistik/obligationsrenter/"
current_url = xml2::read_html(source_url) %>%
  html_node("#wrapper > div > div.sectionB > div.container > div > div.span8 > p:nth-child(10) > a") %>% 
  rvest::html_attr("href")
xlsx_url = paste0("https://finansdanmark.dk/",current_url)

df_interest = openxlsx::read.xlsx(xlsxFile = xlsx_url,startRow = 3)

df_interest$Date = as.Date(paste(df_interest$År, df_interest$Uge, 1, sep="-"), "%Y-%U-%u")
df_interest = df_interest %>% 
  dplyr::select(Date,Kort.rente,Lang.rente) %>% 
  dplyr::mutate( CurveLongShort = Lang.rente - Kort.rente ) %>% 
  gather(STAT,VALUE,Kort.rente:CurveLongShort) %>% 
  # dplyr::mutate(VALUE=TTR::RSI(VALUE,n=14)) %>% 
  crossing(PROPERTY_TYPE=c("FLAT","HOUSE")) %>% 
  dplyr::mutate(PROPERTY_TYPE=recode(PROPERTY_TYPE, 'HOUSE'='Parcel-/rækkehuse', 'FLAT'='Ejerlejlighed')) %>% 
  dplyr::mutate(INDEX=scale(VALUE,center = TRUE,scale = TRUE)) %>% 
  dplyr::rename(DATE=Date)
```


```{r}

df.adjustments = 
  openxlsx::read.xlsx(xlsxFile = "Data/20223617848365363032BM011_2.xlsx",startRow = 3) %>% 
  setNames(.,c("ZIP","DATE","STAT","HOUSE","FLAT")) %>% 
  tidyr::fill(ZIP,.direction="down") %>% 
  tidyr::fill(DATE,.direction="down") %>% 
  gather(PROPERTY_TYPE,VALUE,HOUSE,FLAT) %>% 
  filter(!VALUE=="..") %>% 
  dplyr::mutate(VALUE=as.integer(VALUE)) %>% 
  unite(STAT,STAT,PROPERTY_TYPE) %>% 
  spread(STAT,VALUE) %>% 
  dplyr::mutate(ADJUST_HOUSE=(`Realiseret handelspris_HOUSE`/`Første udbudspris_HOUSE`)-1) %>% 
  dplyr::mutate(ADJUST_FLAT=(`Realiseret handelspris_FLAT`/`Første udbudspris_FLAT`)-1) %>% 
  dplyr::select(ZIP,DATE,ADJUST_HOUSE,ADJUST_FLAT) %>% 
  gather(ADJUST_TYPE,VALUE,ADJUST_HOUSE,ADJUST_FLAT) %>% 
  na.omit() %>% 
  separate(ADJUST_TYPE,into=c("STAT","PROPERTY_TYPE")) %>% 
  dplyr::mutate(DATE=lubridate::ceiling_date(as.Date(as.yearqtr(DATE, format = "%YK%q")),"quarters")-days(1)) %>% 
  dplyr::mutate(PROPERTY_TYPE=recode(PROPERTY_TYPE, 'HOUSE'='Parcel-/rækkehuse', 'FLAT'='Ejerlejlighed')) %>% 
  group_by(PROPERTY_TYPE,STAT,ZIP) %>% 
  dplyr::mutate(INDEX=scale(VALUE,center = TRUE,scale = TRUE)) 

```


### All time development

```{r}

df.adjustments %>% 
  bind_rows( df.house_prices ) %>% 
  bind_rows( df_liggetider ) %>% 
  bind_rows( df_interest ) %>% 
  bind_rows( df_BYGV80 ) %>% 
  ggplot(.,aes(x=DATE,y=INDEX,color=STAT)) +
  geom_smooth(fill=NA,span=0.03) +
  facet_wrap(~PROPERTY_TYPE,ncol=1) +
  geom_smooth(data=df_udbud,aes(x=DATE,y=VALUE),color="blue",linetype=2)  +
  scale_x_date(date_breaks = "1 year",date_labels = "%Y") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  theme(legend.position="bottom") +
  geom_vline(data=df_udbud.covid19low.DK,aes(xintercept=DATE)) +
  geom_vline(data=df_udbud.bubblelow.DK,aes(xintercept=DATE)) +
  geom_hline(yintercept = 0) +
  theme_money_printer_go_brrr 
```

```{r}

df_BYGV80 %>% 
  ggplot(.,aes(x=DATE,y=INDEX,color=STAT)) +
  geom_line(color="gray30") +
  geom_smooth(fill=NA) +
  facet_wrap(~PROPERTY_TYPE,ncol=1) +
  geom_smooth(data=df_udbud,aes(x=DATE,y=VALUE),color="blue",linetype=2)  +
  scale_x_date(date_breaks = "1 year",date_labels = "%Y",limits=c(dmy("2004-01-01"),dmy("2008-01-01"))) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  theme(legend.position="bottom") +
  geom_vline(data=df_udbud.covid19low.DK,aes(xintercept=DATE)) +
  geom_vline(data=df_udbud.bubblelow.DK,aes(xintercept=DATE)) +
  geom_hline(yintercept = 0)  +
  theme_money_printer_go_brrr 

```

```{r}
ggplot(df_udbud,aes(x=DATE,y=VALUE,color=ZIP)) +
  geom_line(alpha=0.3) +
  facet_wrap(~PROPERTY_TYPE) +
  theme_money_printer_go_brrr 
```
### COVID 19 lows

```{r}
ggplot(df_udbud,aes(x=DATE,y=VALUE,color=ZIP)) +
  geom_line(alpha=0.3) +
  facet_wrap(~PROPERTY_TYPE)  +
  scale_x_date(limits=c(ymd("2020-01-01"),NA),date_labels = "%b",date_breaks = "3 months")  +
  geom_vline(data=df_udbud.covid19low,aes(xintercept=DATE,color=ZIP),linetype=2,alpha=0.7) +
  theme_money_printer_go_brrr 
```

### Bubble lows

```{r}
ggplot(df_udbud,aes(x=DATE,y=VALUE,color=ZIP)) +
  geom_line(alpha=0.3) +
  facet_wrap(~PROPERTY_TYPE)  +
  scale_x_date(limits=c(ymd("2005-01-01"),ymd("2008-01-01")))  +
  geom_vline(data=df_udbud.bubblelow,aes(xintercept=DATE,color=ZIP),linetype=2,alpha=0.7) +
  theme_money_printer_go_brrr 
```


