---
title: "Boliger med/uden CPR"
author: "CAKU"
date: "`r Sys.Date()`"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
library(pacman)
pacman::p_load(devtools,dkstat,zoo,dplyr,tidyr,ggplot2,lubridate)
options(scipen=999)
source(file = "money_theme.R")

```

# Denmark: Building Occupation

```{r }
BOL101_meta <- dst_meta(table = "BOL101", lang = "da")
BOL101 <- dst_get_data(table = "BOL101", 
                       OMRÅDE=c("Hele landet","Lyngby-Taarbæk"),
                       BEBO=c("Boliger med CPR tilmeldte personer (beboede boliger)",
                              "Boliger uden CPR tilmeldte personer (ubeboede boliger)"),
                       ANVENDELSE=c("Parcel/Stuehuse",
                                    "Række-, kæde- og dobbelthuse",
                                    "Etageboliger"),
                       UDLFORH=c("Beboet af ejer",
                                 "Beboet af lejer",
                                 "Ikke benyttet bolig"),
                       EJER=c("Privatpersoner inkl I/S",
                              "Almene boligselskaber",
                              "A/S, ApS og andre selskaber"),
                       OPFØRELSESÅR="*",
                       Tid="*",
                       lang = "da")

```

```{r}

df_BOL101 = 
  BOL101 %>% 
  group_by(OMRÅDE,TID,ANVENDELSE,BEBO) %>% 
  dplyr::summarise(value=sum(value)) %>% 
  # dplyr::mutate(value=scale(value)) %>% 
  ungroup()

df_BOL101 %>% 
  filter(OMRÅDE=="Hele landet") %>% 
  ggplot(.,aes(x=TID,y=value,color=BEBO)) +
  geom_line() +
  facet_wrap(~ANVENDELSE+BEBO,scales="free") +
  theme(legend.position="bottom") +
  theme_money_printer_go_brrr 
```

## Ratio

```{r}

df_BOL101 = 
  BOL101 %>% 
  group_by(OMRÅDE,TID,ANVENDELSE,BEBO) %>% 
  dplyr::summarise(value=sum(value)) %>% 
  # dplyr::mutate(value=scale(value)) %>% 
  ungroup()

df_BOL101 %>% 
  spread(BEBO,value) %>% 
  dplyr::mutate(ratio=`Boliger med CPR tilmeldte personer (beboede boliger)`/`Boliger uden CPR tilmeldte personer (ubeboede boliger)`) %>% 
  ggplot(.,aes(x=TID,y=ratio,color=ANVENDELSE)) +
  geom_line() +
  facet_wrap(~OMRÅDE,scales="free") +
  theme(legend.position="bottom") +
  theme_money_printer_go_brrr 
```




