---
title: "Recession Prediction"
author: "CAKU"
date: "`r Sys.Date()`"
output: html_document
---

```{r  include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
```

# Recession Prediction

```{r}
library(pacman)
pacman::p_load(fredr,dplyr,tidyr,lubridate,caret,partykit,pROC)
source(file = "money_theme.R")
```

```{r }
readRenviron(path = "Renviron.site")
fredr::fredr_set_key(key = Sys.getenv("FRED_API"))
```


```{r }
dates = data.frame(date=seq.Date(from = ymd("1960-01-01"),to = ymd("2022-02-01"),by="1 day"))
```

```{r}
recession_bool = fredr::fredr("USREC") %>% 
  filter(value==1) %>% 
  dplyr::select(date) %>% 
  dplyr::mutate(Recession=factor("Yes",levels=c("No","Yes")))
```


# Recession Next 6 Months

```{r}
# Skeleton
recession_next_six_months = fredr::fredr("USREC") %>% 
  filter(value==1) %>% 
  dplyr::select(date) %>% 
  dplyr::mutate(minus1mo=date-months(1),
                minus2mo=date-months(2),
                minus3mo=date-months(3),
                minus4mo=date-months(4),
                minus5mo=date-months(5),
                minus6mo=date-months(6)) %>% 
  gather(date_type,date_val,minus1mo:minus6mo) %>% 
  dplyr::mutate(Recession=factor("Yes",levels=c("No","Yes"))) %>% 
  dplyr::select(date_val,Recession) %>% 
  distinct()
recession_next_six_months = dates %>% 
  left_join(recession_next_six_months,by=c("date"="date_val")) %>% 
  dplyr::mutate(Recession=replace_na(Recession,"No"))

# Data frame with predictors
df_yieldcurve = 
  fredr(series_id = "DGS1") %>% 
  bind_rows(fredr(series_id = "DGS2")) %>% 
  bind_rows(fredr(series_id = "DGS3")) %>% 
  bind_rows(fredr(series_id = "DGS5")) %>% 
  bind_rows(fredr(series_id = "DGS7")) %>% 
  bind_rows(fredr(series_id = "DGS10")) %>% 
  bind_rows(fredr(series_id = "DGS20")) %>% 
  bind_rows(fredr(series_id = "DGS30")) %>% 
  bind_rows(fredr(series_id = "DGS1MO")) %>% 
  bind_rows(fredr(series_id = "DGS3MO")) %>% 
  bind_rows(fredr(series_id = "DGS6MO")) %>% 
  bind_rows(fredr(series_id = "DFF")) %>% 
  bind_rows(fredr(series_id = "MORTGAGE30US")) %>% 
  dplyr::select(-realtime_start,
                -realtime_end)

df_checkboard = expand.grid(date=seq.Date(from = min(df_yieldcurve$date),to = ymd("2022-02-01"),by="1 day"),
                            series_id=unique(df_yieldcurve$series_id),
                            joined_series=unique(df_yieldcurve$series_id))

df_yieldcurve_predictors = df_checkboard %>% 
  left_join(df_yieldcurve) %>% 
  left_join(df_yieldcurve,by=c("joined_series"="series_id","date"="date")) %>% 
  filter(series_id != joined_series) %>% 
  tidyr::fill(value.x,.direction="updown") %>% 
  tidyr::fill(value.y,.direction="updown") %>% 
  dplyr::mutate(spread=value.x-value.y) %>% 
  dplyr::select(series_id,joined_series,date,spread) %>% 
  unite(series_id,series_id,joined_series) %>% 
  spread(series_id,spread)

# Joined
df_fit_recession6mos =
  df_yieldcurve_predictors %>% 
  inner_join(recession_next_six_months)

# Split
df.training = df_fit_recession6mos %>% filter(date<ymd("2018-01-01"))
df.test = df_fit_recession6mos %>% filter(date>ymd("2018-01-01"))

df.training.na_omit = na.omit( df_fit_recession6mos %>% filter(date<ymd("2018-01-01")) )
df.test.na_omit = na.omit( df_fit_recession6mos %>% filter(date>ymd("2018-01-01")) )
```


```{r}
# Control object
trcontrol = caret::trainControl(method = "repeatedcv",
                                number=5,
                                repeats=3,
                                summaryFunction = twoClassSummary,
                                classProbs = TRUE,
                                verboseIter=TRUE)
```


```{r}
# RPART
fit.rpart = caret::train(x = df.training.na_omit %>% dplyr::select(-Recession,-date),
                         y = df.training.na_omit$Recession,
                         metric="ROC",
                         method="rpart",
                         trControl=trcontrol,
                         tuneLength=20)
fit.rpart
plot(as.party(fit.rpart$finalModel))
```


```{r eval=F}
# GLM STEP AIC
fit.glmStepAIC = MASS::stepAIC(glm(Recession~.,
                  data = df_fit_recession6mos %>% dplyr::select(-date) %>% na.omit(),
                  family="binomial"))
summary( fit.glmStepAIC )
```


```{r }
# RANDOM FOREST
fit.rf = caret::train(x = df.training.na_omit %>% dplyr::select(-Recession,-date),
                         y = df.training.na_omit$Recession,
                         metric="ROC",
                         ntree=100,
                         method="rf",
                         tuneGrid=data.frame(mtry=c(1,2,5,10,20,50)),
                         trControl=trcontrol)
fit.rf
varImp(fit.rf)
```


```{r}
# Validate
pred_rpart = predict(fit.rpart,df.test,type = "prob")[,2]
# pred_glmStepAIC = predict(fit.glmStepAIC,df.test,type = "response")
pred_rf = predict(fit.rf,df.test,type = "prob")[,2]

roc_rpart = pROC::roc(predictor = pred_rpart,response = df.test$Recession)
# roc_glm = pROC::roc(predictor = pred_glmStepAIC,response = df.test$Recession)
roc_rf = pROC::roc(predictor = pred_rf,response = df.test$Recession)
```


```{r}
plot(roc_rf)
```

```{r}
roc_glm
```


```{r}
cicoords_rf = ci.coords(roc_rf,x="best",best.method="youden",best.policy="random")
cicoords_cutoff = cicoords_rf$threshold[2]
```

## Extrapolate

```{r}

df.extrapolate = df.test
df.extrapolate$risk = predict(fit.rf,df.extrapolate,type = "prob") %>% pull(Yes)

ggplot(df.extrapolate,aes(x=date,y=risk)) +
  geom_line() +
  scale_y_continuous(labels=scales::percent) +
  geom_hline(yintercept = cicoords_cutoff,linetype=2)
```


## Backtest

```{r}

df.backtest = df.training %>% 
  dplyr::mutate(type="Training") %>% 
  bind_rows(df.test) %>% 
  dplyr::mutate(type=tidyr::replace_na(type,"Test"))
df.backtest$risk = predict(fit.rf,df.backtest,type = "prob") %>% pull(Yes)

ggplot(df.backtest,aes(x=date,y=risk)) +
  geom_line(aes(color=type)) +
  scale_y_continuous(labels=scales::percent) +
  scale_x_date(date_breaks = "3 years",date_labels = "%Y",limits=c(ymd("1980-01-01",NA))) +
  geom_hline(yintercept = cicoords_cutoff,linetype=2) +
  theme_bw() +
  theme(legend.position="bottom")

```

