---
title: "ECB Yields"
author: "Christian Kruse"
date: "4/2/2022"
output: html_document
---

```{r ecb,include=FALSE }
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
```

# ECB Yield

```{r }
library(pacman)
pacman::p_load(ecb,tidyr,dplyr,glue,data.table,ggplot2)
source(file = "money_theme.R")
```

```{r}
# Deposit Rate
df_ECB_DepositRate = ecb::get_data(key = glue("FM.D.U2.EUR.4F.KR.DFR.LEV"))   %>% 
  dplyr::mutate(obstime=ymd(obstime),
                Yield="0M") %>% 
    dplyr::select(Yield,obstime,obsvalue)
  
# Yields
yields = c( paste0(c(3,6,9),"M") , paste0(seq(30),"Y"))
df_ECB_yields = rbindlist(lapply(yields,function(yield) {
  ecb::get_data(key = glue("YC.B.U2.EUR.4F.G_N_A.SV_C_YM.SR_{yield}"))  %>% 
  dplyr::mutate(obstime=ymd(obstime),
                Yield=yield) %>% 
    dplyr::select(Yield,obstime,obsvalue)
}))

# Combined
df_ECB_yields =
  df_ECB_DepositRate %>% 
  bind_rows(df_ECB_yields) %>% 
  dplyr::mutate(Yield_Numeric=as.integer(paste0(recode(Yield,
                               '0M'='0',
                               '3M'='3',
                               '6M'='6',
                               '9M'='9',
                               '1Y'=paste0(glue("{1*12}")),
                               '2Y'=paste0(glue("{2*12}")),
                               '3Y'=paste0(glue("{3*12}")),
                               '4Y'=paste0(glue("{4*12}")),
                               '5Y'=paste0(glue("{5*12}")),
                               '6Y'=paste0(glue("{6*12}")),
                               '7Y'=paste0(glue("{7*12}")),
                               '8Y'=paste0(glue("{8*12}")),
                               '9Y'=paste0(glue("{9*12}")),
                               '10Y'=paste0(glue("{10*12}")),
                               '11Y'=paste0(glue("{11*12}")),
                               '12Y'=paste0(glue("{12*12}")),
                               '13Y'=paste0(glue("{13*12}")),
                               '14Y'=paste0(glue("{14*12}")),
                               '15Y'=paste0(glue("{15*12}")),
                               '16Y'=paste0(glue("{16*12}")),
                               '17Y'=paste0(glue("{17*12}")),
                               '18Y'=paste0(glue("{18*12}")),
                               '19Y'=paste0(glue("{19*12}")),
                               '20Y'=paste0(glue("{20*12}")),
                               '21Y'=paste0(glue("{21*12}")),
                               '22Y'=paste0(glue("{22*12}")),
                               '23Y'=paste0(glue("{23*12}")),
                               '24Y'=paste0(glue("{24*12}")),
                               '25Y'=paste0(glue("{25*12}")),
                               '26Y'=paste0(glue("{26*12}")),
                               '27Y'=paste0(glue("{27*12}")),
                               '28Y'=paste0(glue("{28*12}")),
                               '29Y'=paste0(glue("{29*12}")),
                               '30Y'=paste0(glue("{30*12}")))))) %>% 
  dplyr::mutate(obsvalue=obsvalue/100)
```

## Yield Curve

```{r}

breaks_ = unique(df_ECB_yields$Yield_Numeric)
labels_ = unique(df_ECB_yields$Yield)

df_ECB_yields %>% 
  group_by(Yield) %>% 
  filter(obstime==max(obstime)) %>% 
  ggplot(.,aes(x=Yield_Numeric,y=obsvalue)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(labels = labels_,
                     breaks = breaks_) +
  scale_y_continuous(breaks = seq(-0.5,0.5,by=0.0025),labels = scales::percent)+
  theme_money_printer_go_brrr(base_size=12) +
  theme(axis.text.x=element_text(angle=45,hjust=1,size=8))

```

```{r}

checkboard_yields = c('1M','3M','6M','1Y','2Y','3Y','5Y','7Y','10Y','20Y','30Y')

df_checkboard = expand.grid(Yield=checkboard_yields,
                            Joined_Yield=checkboard_yields)

df_yield_checkboard = 
  df_checkboard %>% 
  inner_join(df_ECB_yields) %>% 
  inner_join(df_ECB_yields,by=c("Joined_Yield"="Yield","obstime"="obstime")) %>% 
  dplyr::mutate(spread=obsvalue.x-obsvalue.y) %>% 
  dplyr::mutate(label_=ifelse(spread<0,spread,NA)) %>% 
  dplyr::mutate(label_=scales::percent(x = label_,accuracy = 0.01,)) %>%
  dplyr::select(Yield,Joined_Yield,obstime,spread,label_) %>% 
  dplyr::mutate(Yield=factor(Yield,levels=checkboard_yields),
                Joined_Yield=factor(Joined_Yield,levels=checkboard_yields))

df_yield_checkboard %>% 
  group_by(Yield,Joined_Yield) %>% 
  filter(obstime==max(obstime)) %>% 
  ungroup() %>% 
  dplyr::mutate(spread=ifelse(Yield==Joined_Yield,NA,spread)) %>% 
  ggplot(.,aes(x=Yield,y=Joined_Yield)) +
  geom_tile(aes(fill=spread)) +
  scale_fill_gradient2(low="green",high="red",midpoint=0,na.value = "gray70") +
  theme_money_printer_go_brrr(base_size=12) +
  theme(axis.text.x=element_text(angle=45,hjust=1),
        legend.position="bottom")+
  geom_text(aes(label=label_),size=3.5)
```


## Spreads

### 2s10s

```{r}

df_ECB_yields %>% 
  dplyr::select(-Yield_Numeric) %>% 
  filter(Yield %in% c("2Y","10Y")) %>% 
  spread(Yield,obsvalue) %>% 
  dplyr::mutate(spread=(`10Y`-`2Y`)) %>% 
  ggplot(.,aes(x=obstime,y=spread)) +
  geom_line() +
  geom_hline(yintercept = 0,linetype=2) + 
  scale_x_date(date_breaks = "1 year",date_labels = "%Y") +
  scale_y_continuous(labels = scales::percent,breaks = seq(-0.1,1,by=0.0025)) + 
  theme_money_printer_go_brrr(base_size=12) +
  labs(title="Spread: 2Y - 10Y",
       x="Date",
       y="Spread (%)",
       caption = timestamp_caption()
       )
```

## Predict Yield

```{r}

num_trees=1000
tune_grid=data.frame(mtry=c(1,2))

train_control = caret::trainControl(method = "repeatedcv",number = 5,repeats = 5)

df_DF = 
  df_ECB_yields %>% 
  filter(Yield=="0M") %>% 
  dplyr::select(obstime,obsvalue)

df_predict_DF = df_yield_checkboard %>% 
  filter(Yield!=Joined_Yield) %>% 
  dplyr::mutate(one_year_ahead=obstime+years(1)) %>% 
  left_join(df_DF,by=c("one_year_ahead"="obstime")) %>% 
  unite(Yield,Yield,Joined_Yield) %>% 
  dplyr::select(obstime,Yield,spread,obsvalue) %>% 
  dplyr::mutate(Yield=paste0("S",Yield)) %>% 
  spread(Yield,spread)

fit_DF = caret::train(x = df_predict_DF %>% 
                              na.omit %>% 
                              dplyr::select(-obstime,-obsvalue) %>% 
                              data.frame(),
                         y = df_predict_DF %>% 
                           na.omit %>% 
                           .[["obsvalue"]],
                         method = "rf",
                         tuneGrid=tune_grid,
                         ntree=num_trees,
                         metric = "RMSE",
                         trControl=train_control)
fit_DF
```

## Extrapolate

```{r}

df_predict_DF %>% 
  dplyr::mutate(pred_DF=predict(fit_DF,.)) %>% 
  dplyr::select(obstime,obsvalue,pred_DF) %>% 
  dplyr::mutate(obstime=obstime+years(1)) %>%
  gather(pred,val,obsvalue:pred_DF) %>%
  crossing(one_year=c(TRUE,FALSE)) %>% 
  dplyr::mutate(obstime=ifelse(one_year,
                            ifelse(obstime>=Sys.Date()-years(1),obstime,NA),obstime)) %>% 
  filter(!is.na(obstime)) %>% 
  dplyr::mutate(obstime=as.Date(obstime,origin="1970-01-01")) %>%
  ggplot(.,aes(x=obstime,y=val,color=pred)) +
  geom_line() +
  scale_x_date(date_breaks = "1 year",date_labels = "%Y") +
  scale_y_continuous(labels = scales::percent) +
  theme_money_printer_go_brrr(base_size=12) +
  # theme(axis.text.x=element_text(angle=45,hjust=1)) +
  geom_vline(xintercept = Sys.Date(),linetype=2) +
  geom_hline(yintercept = 0,linetype=2) +
  facet_wrap(~one_year,scales="free",ncol=1)
```

## ECB to Danish Yields

```{r}

df_DK10Y = ecb::get_data(key = "IRS.M.DK.L.L40.CI.0000.DKK.N.Z")  %>% 
  dplyr::mutate(obstime=ymd(paste0(obstime,"-01")),
                Yield="10Y",
                dk_obsvalue=obsvalue/100) %>% 
    dplyr::select(Yield,obstime,dk_obsvalue)

df_DK3MO = ecb::get_data(key = "FM.M.DK.DKK.DS.MM.CIBOR3M.ASKA")  %>% 
  dplyr::mutate(obstime=ymd(paste0(obstime,"-01")),
                Yield="3M",
                dk_obsvalue=obsvalue/100) %>% 
    dplyr::select(Yield,obstime,dk_obsvalue)

df_ECB_DK =
  df_ECB_yields %>% 
  filter(Yield %in% c("3M","10Y")) %>% 
  inner_join( bind_rows(df_DK10Y,df_DK3MO) ) %>% 
  dplyr::mutate(spread=dk_obsvalue-obsvalue) %>% 
  dplyr::select(-Yield_Numeric) %>% 
  gather(stat,val,obsvalue:spread) %>% 
  dplyr::mutate(stat=recode(stat,
                            'obsvalue'='EU 3 Mo.',
                            'spread'='DK-EU Spread',
                            'dk_obsvalue'='DK Interbank 3 Mo.'))


df_ECB_DK %>% 
  ggplot(.,aes(x=obstime,y=val,color=stat)) +
  geom_line() +
  facet_wrap(~Yield) +
  scale_y_continuous(labels = scales::percent,breaks = seq(-0.01,0.1,by=0.005)) +
  scale_x_date(date_breaks = "1 year",date_labels = "%Y") +
  geom_hline(yintercept = 0,linetype=2) +
  theme_money_printer_go_brrr(base_size=12)  +
  labs(title="Spread: DK Interbank 3MO - EU 3 Month Bond",
       x="Date",
       y="Spread (%)",
       caption = timestamp_caption()
       )


```

