---
title: "Indicators"
author: "Christian Kruse"
date: "`r Sys.Date()`"
output: html_document
---

```{r  include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
options(scipen=999)
```

```{r}

if (!require(pacman)) { install.packages("pacman") }
pacman::p_load(fredr,
               dplyr,
               tidyr,
               lubridate,
               caret,
               partykit,
               pROC,
               gganimate,
               devtools,
               httr,
               DT,
               httr,
               visNetwork,
               dkstat,
               data.table,
               pROC,
               igraph,
               visNetwork,
               rPref,
               progress,
               quantmod,
               rvest,
               ggrepel)
source(file = "money_theme.R")
```

# Indicators


```{r }
readRenviron(path = "Renviron.site")
fredr::fredr_set_key(key = Sys.getenv("FRED_API"))
```

## ETFs data

```{r}

df_etfs = openxlsx::read.xlsx(xlsxFile = "Chapters/01_Indicators/etf_list.xlsx")

df_etf_yahoo = rbindlist(lapply(df_etfs$Ticker,function(ticker) {
      temp_df = getSymbols(ticker, env = NULL) %>% 
      as.data.frame(.) %>% 
      dplyr::mutate(Date=row.names(.)) %>% 
      dplyr::mutate(Date=gsub("X","",Date)) %>% 
      dplyr::mutate(Date=ymd(Date)) %>% 
      dplyr::select(c(7,1)) %>% 
      setNames(.,c("date","value")) %>% 
      dplyr::mutate(series_id=ticker)# %>% 
      # tidyr::complete(date=seq.Date(from=min(date,na.rm=T),to=Sys.Date(),by="1 day")) %>% 
      # tidyr::fill(value,.direction = "down")  %>% 
      # tidyr::fill(series_id,.direction = "down") 
      
      row.names(temp_df) = NULL
      return( temp_df )
}))

```

## Data


```{r }
# BYGV80_meta <- dst_meta(table = "BYGV80", lang = "da")
BYGV80 <- dst_get_data(table = "BYGV80", 
                       BYGFASE="*",
                       ANVENDELSE="*",
                       Tid="*",
                       lang = "da") %>% 
  group_by(BYGFASE,ANVENDELSE) %>% 
  arrange(BYGFASE,ANVENDELSE,TID) %>% 
  filter(ANVENDELSE %in% c("Parcelhuse")) %>% 
  ungroup() %>% 
  dplyr::select(BYGFASE,
                TID,
                value) %>% 
  dplyr::rename(series_id=BYGFASE,
                date=TID)
  

# BYG1_meta <- dst_meta(table = "BYG1", lang = "da")
BYG1 <- dst_get_data(table = "BYG1", 
                       BRANCHE07="*",
                       SÆSON="*",
                       ART="*",
                       Tid="*",
                       lang = "da") %>% 
  filter(SÆSON=="Sæsonkorrigeret") %>% 
  dplyr::mutate(filler="BYG1") %>% 
  unite(series_id,filler,BRANCHE07,ART,sep = "_") %>% 
  dplyr::select(series_id,
                TID,
                value) %>% 
  dplyr::rename(date=TID)

# PRIS90_meta <- dst_meta(table = "PRIS90", lang = "da")
PRIS90 <- dst_get_data(table = "PRIS90", 
                       ENHED="*",
                       BOLTYP="*",
                       Tid="*",
                       lang = "da") %>% 
  dplyr::rename(date=TID) %>% 
  filter(ENHED=="Indeks")  %>% 
  unite(BOLTYP,BOLTYP,ENHED) %>% 
  dplyr::rename(series_id=BOLTYP)

# BYG42_meta <- dst_meta(table = "BYG42", lang = "da")
BYG42 <- dst_get_data(table = "BYG42", 
                       HINDEKS="*",
                       DINDEKS="*",
                       ART="*",
                       TAL="*",
                       Tid="*",
                       lang = "da") %>% 
  dplyr::rename(date=TID) %>% 
  filter(DINDEKS=="Byggeomkostningsindeks i alt") %>% 
  filter(TAL=="Indeks") %>% 
  filter(ART %in% c("Materialer","Arbejdsomkostninger")) %>% 
  dplyr::mutate(filler="BYG42") %>% 
  unite(series_id,filler,HINDEKS,DINDEKS,ART,sep="_")%>% 
  dplyr::select(series_id,
                date,
                value) 

```


### FinansDanmark

```{r}

source_url = "https://finansdanmark.dk/tal-og-data/boligstatistik/obligationsrenter/"
current_url = xml2::read_html(source_url) %>%
  html_node("body > main > div > div.page-header > div.page-header__content > div > div.row > div.col-12.col-md-8 > div > p:nth-child(11) > a") %>% 
  rvest::html_attr("href")
xlsx_url = paste0("https://finansdanmark.dk/",current_url)

df_interest = openxlsx::read.xlsx(xlsxFile = xlsx_url,startRow = 1)
df_interest$År[1] = 1997
df_interest = df_interest %>% fill(År,.direction = "down")
df_interest$Date = as.Date(paste(df_interest$År, df_interest$Uge, 1, sep="-"), "%Y-%U-%u")
df_interest = df_interest %>% 
  dplyr::select(Date,Kort.rente,Lang.rente) %>% 
  dplyr::mutate( CurveLongShort = Lang.rente - Kort.rente ) %>% 
  gather(series_id,value,CurveLongShort,Lang.rente,Kort.rente) %>% 
  dplyr::rename(date=Date) %>% 
  dplyr::select(date,value,series_id)

```

### FRED

```{r}
series_ids = unique(c(# "T10Y2Y",
               "T5YIFR",
               "BAA10Y",
               # "T10Y3M",
               "CPIAUCSL",
               "DFF",
               "ACTLISCOUUS",
               "MORTGAGE30US",
               "COMPUTSA",
               # "RRVRUSQ156N",
               "UMCSENT",
               # "BAMLH0A0HYM2",
               # "RHORUSQ156N",
               "T10YIE",
               "HOUST1F",
               # "BAMLH0A0HYM2",
               "COMPU1USA",
               "M2V",
               # "BAMLC0A4CBBB",
               "PCEPI",
               "AUTHNOTT",
               "PSAVERT",
               # "RRPONTSYD",
               "PERMIT",
               "M1SL",
               "PERMIT1",
               # "T10Y3M",
               "INDPRO",
               # "BAMLC0A4CBBB",
               # "NFCI",
               "CORESTICKM159SFRBATL",
               "PAYEMS",
               "CIVPART",
               "MDSP",
               "M2SL",
               "UNRATE",
               "AUTHNOT1U",
               "HOUST",
               "ICSA",
               "DGS10",
               "DGS20",
               "DGS30",
               "DGS5",
               "DGS2",
               "DGS1",
               "CSUSHPINSA",
               "GDP",
               # "GDPC1",
               # "DFII10",
               # "TDSP",
               "WALCL",
               "MSPUS"))

df_macro_fred = rbindlist(lapply(series_ids,function(series_id) {
  fredr::fredr_series_observations(series_id = series_id) %>% 
  dplyr::select(date,value) %>% 
    dplyr::mutate(series_id=series_id) #%>% 
    # tidyr::complete(date=seq.Date(from=min(date,na.rm=T),to=Sys.Date(),by="1 day")) %>% 
    # tidyr::fill(value,.direction = "down")  %>% 
    # tidyr::fill(series_id,.direction = "down") 
}))
```

### Yahoo

```{r}

series_ids_yahoo = unique(c("GC=F",
                            "SI=F",
                            "DX-Y.NYB",
                            "BTC-USD",
                            "PA=F",
                            "^IXIC",
                            "^GSPC",
                            "^OMXC25",
                            "USDDKK=X"))

df_macro_yahoo = rbindlist(lapply(series_ids_yahoo,function(ticker) {
      temp_df = getSymbols(ticker, env = NULL) %>% 
      as.data.frame(.) %>% 
      dplyr::mutate(Date=row.names(.)) %>% 
      dplyr::mutate(Date=gsub("X","",Date)) %>% 
      dplyr::mutate(Date=ymd(Date)) %>% 
      dplyr::select(c(7,1)) %>% 
      setNames(.,c("date","value")) %>% 
      dplyr::mutate(series_id=ticker) #%>% 
      # tidyr::complete(date=seq.Date(from=min(date,na.rm=T),to=Sys.Date(),by="1 day")) %>% 
      # tidyr::fill(value,.direction = "down")  %>% 
      # tidyr::fill(series_id,.direction = "down") 
      
      row.names(temp_df) = NULL
      return( temp_df )
})) %>% 
  bind_rows( df_etf_yahoo )
```

## Combine

### All Data

```{r}

df_all = df_macro_yahoo %>% 
  bind_rows( df_macro_fred ) %>% 
  bind_rows( df_etf_yahoo ) %>% 
  bind_rows(df_interest) %>% 
  bind_rows(BYG42) %>% 
  bind_rows(PRIS90) %>%
  bind_rows(BYGV80)
all_ids = unique(df_all$series_id)

rm(df_macro_yahoo)
rm(df_macro_fred)
rm(df_etf_yahoo)
gc()
```

## Combine

```{r}
df_combinations = expand.grid(x1=all_ids,
                              x2=all_ids) %>%
  filter(!x1==x2)

# df_combinations = data.frame(t(combn(all_ids,2))) %>% 
  # dplyr::rename(x1=X1,
  #               x2=X2)
```

## Cross correlations

```{r}
# df_combinations_split = split(df_combinations,df_combinations$x1)
df_combinations_split = split(df_combinations, (seq(nrow(df_combinations))) %/% 2000) 
```


```{r}
calc_ccf = function(data) {
  ## 30 days
  ccf_results = ccf(data$value.x,data$value.y,lag.max = 30,plot = FALSE)
  best_corr_index_30 = which(abs(ccf_results$acf)==max(abs(ccf_results$acf)))
  best_corr_time_30 = ccf_results$lag[best_corr_index_30]
  best_corr_value_30 = ccf_results$acf[best_corr_index_30]
  ## 365 days
  ccf_results = ccf(data$value.x,data$value.y,lag.max = 365,plot = FALSE)
  best_corr_index_365 = which(abs(ccf_results$acf)==max(abs(ccf_results$acf)))
  best_corr_time_365 = ccf_results$lag[best_corr_index_365]
  best_corr_value_365 = ccf_results$acf[best_corr_index_365]
  ## 1825 days
  ccf_results = ccf(data$value.x,data$value.y,lag.max = 1825,plot = FALSE)
  best_corr_index_1825 = which(abs(ccf_results$acf)==max(abs(ccf_results$acf)))
  best_corr_time_1825 = ccf_results$lag[best_corr_index_1825]
  best_corr_value_1825 = ccf_results$acf[best_corr_index_1825]
  
  data.frame(best_corr_time_30,best_corr_value_30,
             best_corr_time_365,best_corr_value_365,
             best_corr_time_1825,best_corr_value_1825)
}
df_ccfs = do.call("rbind",lapply(df_combinations_split,function(split_) { split_ %>% 
  inner_join(df_all,by=c("x1"="series_id")) %>% 
  inner_join(df_all,by=c("x2"="series_id","date"="date")) %>% 
  dplyr::select(-date) %>% 
  na.omit() %>% 
  group_by(x1,x2) %>% 
  do(calc_ccf(.))
}))
```

```{r}
df_best_corr = df_ccfs %>% 
  ungroup() %>% 
  dplyr::select(x1,x2,best_corr_time_30,best_corr_time_365,best_corr_time_1825) %>% 
  gather(corr_time,corr_value, best_corr_time_30, best_corr_time_365, best_corr_time_1825 ) %>% 
  arrange(x1,x2) %>% 
  group_by(x1,x2) %>% 
  filter(abs(corr_value)==max(abs(corr_value))) %>% 
  dplyr::mutate(corr_time_min=as.numeric(gsub("best_corr_time_","",corr_time))) %>% 
  group_by(x1,x2,corr_value) %>% 
  filter(corr_time_min==min(corr_time_min)) %>% 
  ungroup() %>% 
  dplyr::select(x1,x2,corr_time)

df_best_corr = df_ccfs %>% 
  ungroup() %>% 
  gather(corr_time,corr_value, best_corr_time_30, best_corr_time_365, best_corr_time_1825 )  %>% 
  gather(corr_time_best,corr_time_value, best_corr_value_30, best_corr_value_365, best_corr_value_1825 ) %>% 
  inner_join(df_best_corr) %>% 
  filter(gsub("best_corr_time_","",corr_time) == gsub("best_corr_value_","",corr_time_best)) %>% 
  dplyr::select(x1,x2,corr_value,corr_time_value)
```

```{r}
df_best_corr %>% 
  ggplot(.,aes(x=corr_value,y=corr_time_value)) +
  geom_point() +
  geom_vline(xintercept = 0,linetype=2) +
  geom_hline(yintercept = 0,linetype=2) +
  scale_y_continuous(limits = c(-1,1),breaks = seq(-1,1,by=0.1)) +
  scale_x_continuous(breaks = seq(-10,10,by=1)*365,labels=seq(-10,10,by=1))
```

## Descriptive

### Leading

```{r}
df_best_corr %>% 
  filter(corr_time_value>0.8) %>% 
  filter(corr_value<0-30) %>% 
  arrange(corr_value) %>% 
  group_by(x1) %>% 
  dplyr::summarize(count=n(),
                   median=scales::number(median(corr_value),accuracy=1),
                   corr=scales::number(median(corr_time_value),accuracy=0.01)) %>% 
  arrange(desc(count)) %>% 
  datatable()
```

### Coincident

```{r}
df_best_corr %>% 
  filter(corr_time_value>0.8) %>% 
  filter(corr_value>=-30,corr_value<=30) %>% 
  arrange(corr_value) %>% 
  group_by(x1) %>% 
  dplyr::summarize(count=n(),
                   median=scales::number(median(corr_value),accuracy=1),
                   corr=scales::number(median(corr_time_value),accuracy=0.01)) %>% 
  arrange(desc(count)) %>% 
  datatable()
```


### Lagging

```{r}
df_best_corr %>% 
  filter(corr_time_value>0.8) %>% 
  filter(corr_value>30) %>% 
  arrange(corr_value) %>% 
  group_by(x1) %>% 
  dplyr::summarize(count=n(),
                   median=scales::number(median(corr_value),accuracy=1),
                   corr=scales::number(median(corr_time_value),accuracy=0.01)) %>% 
  arrange(desc(count)) %>% 
  datatable()
```


## Main graph

```{r}
normalize_strength <- function(strength, min_width, max_width) {
  normalized_strength <- (strength - min(strength)) / (max(strength) - min(strength))
  arrow_width <- normalized_strength * (max_width - min_width) + min_width
  return(arrow_width)
}
```


```{r}

# Create a data frame representing the causal structure
causal_structure = df_best_corr %>% 
  filter(abs(corr_time_value)>0.9) %>% 
  dplyr::rename(from=x1,
                to=x2) %>% 
  dplyr::mutate(sign=ifelse(corr_time_value>0,"positive","negative"),
                strength=scales::rescale(abs(corr_time_value),to = c(0,1),from = c(0,1))) %>% 
  dplyr::select(from,to,sign,strength)

# Convert the data frame to edge_directions
edge_directions <- as.vector(t(causal_structure[, c("from", "to")]))

# Create a graph object with edge_directions
g <- graph(edge_directions, directed = TRUE)

# Create a named vector of colors for positive and negative relationships
edge_colors <- c("positive" = "blue", "negative" = "red")

# Map the colors and thickness to the edges based on the 'sign' and 'strength' columns in causal_structure
E(g)$color <- edge_colors[causal_structure$sign]

normalized_strength <- normalize_strength(causal_structure$strength, min_width = 0.5, max_width = 2)
E(g)$width <- normalized_strength

# Plot the causal graph with colored and thickness-scaled arrows
plot(g, vertex.label.family = "sans", vertex.label.font = 2, vertex.label.cex = 0.6, edge.arrow.size = 0.2)

```

## Individual patterns

### DK Long Interest Rate

```{r}
df_best_corr %>%
  ungroup() %>% 
  filter(x1 %in% c("Lang.rente")) %>% 
  filter(abs(corr_time_value) > 0.85) %>% 
  dplyr::mutate(corr_time_value=scales::number(corr_time_value,0.01)) %>% 
  arrange(desc(corr_time_value)) %>% 
  datatable()
```


```{r}
corr_extra = data.frame(x1=all_ids,
                        x2=all_ids,
                        corr_time_value=1)

filtered_cor_df <- df_best_corr %>%
  ungroup() %>% 
  filter(x1 %in% c("Lang.rente","CIVPART","DGS20","M2SL","PCEPI","TLT")) %>% 
  filter(abs(corr_time_value) > 0.85)

# Create a nodes data frame
nodes <- data.frame(id = unique(c(filtered_cor_df$x1, filtered_cor_df$x2)), label = unique(c(filtered_cor_df$x1, filtered_cor_df$x2)))

# Create an edges data frame
edges <- filtered_cor_df %>%
  mutate(color = if_else(corr_time_value > 0, "green", "red"),
         width = scales::rescale(abs(corr_time_value),to=c(0,30))) %>%
  dplyr::select(from = x1, to = x2, color, width)

# Create a visNetwork graph
visNetwork(nodes, edges) %>%
  visIgraphLayout() %>%
  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%
  visInteraction(navigationButtons = TRUE)

```



### DK Houseprices

```{r}
df_best_corr %>%
  ungroup() %>% 
  filter(x1 %in% c("Enfamiliehuse_Indeks")) %>% 
  filter(abs(corr_time_value) > 0.85) %>% 
  dplyr::mutate(corr_time_value=scales::number(corr_time_value,0.01)) %>% 
  arrange(desc(corr_time_value)) %>% 
  datatable()
```


```{r}
corr_extra = data.frame(x1=all_ids,
                        x2=all_ids,
                        corr_time_value=1)

filtered_cor_df <- df_best_corr %>%
  ungroup() %>% 
  filter(x1 %in% c("Enfamiliehuse_Indeks","PCEPI","CSUSHPINSA","M2SL","PCEPI","TLT","AUTHNOTT","Byggeri under opførelse","CurveLongShort","Lang.Rente")) %>% 
  filter(abs(corr_time_value) > 0.85)

# Create a nodes data frame
nodes <- data.frame(id = unique(c(filtered_cor_df$x1, filtered_cor_df$x2)), label = unique(c(filtered_cor_df$x1, filtered_cor_df$x2)))

# Create an edges data frame
edges <- filtered_cor_df %>%
  mutate(color = if_else(corr_time_value > 0, "green", "red"),
         width = scales::rescale(abs(corr_time_value),to=c(0,30))) %>%
  dplyr::select(from = x1, to = x2, color, width)

# Create a visNetwork graph
visNetwork(nodes, edges) %>%
  visIgraphLayout() %>%
  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%
  visInteraction(navigationButtons = TRUE)

```


### Employment

```{r}
df_best_corr %>%
  ungroup() %>% 
  filter(x1 %in% c("PAYEMS")) %>% 
  filter(abs(corr_time_value) > 0.85) %>% 
  dplyr::mutate(corr_time_value=scales::number(corr_time_value,0.01)) %>% 
  arrange(desc(corr_time_value)) %>% 
  datatable()
```


```{r}
corr_extra = data.frame(x1=all_ids,
                        x2=all_ids,
                        corr_time_value=1)

filtered_cor_df <- df_best_corr %>%
  ungroup() %>% 
  filter(x1 %in% c("PAYEMS","INDPRO","PCEPI","CPIAUCSL","MSPUS","CSUSHPINSA")) %>% 
  filter(abs(corr_time_value) > 0.85)

# Create a nodes data frame
nodes <- data.frame(id = unique(c(filtered_cor_df$x1, filtered_cor_df$x2)), label = unique(c(filtered_cor_df$x1, filtered_cor_df$x2)))

# Create an edges data frame
edges <- filtered_cor_df %>%
  mutate(color = if_else(corr_time_value > 0, "green", "red"),
         width = scales::rescale(abs(corr_time_value),to=c(0,30))) %>%
  dplyr::select(from = x1, to = x2, color, width)

# Create a visNetwork graph
visNetwork(nodes, edges) %>%
  visIgraphLayout() %>%
  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%
  visInteraction(navigationButtons = TRUE)

```


### NASDAQ

```{r}
df_best_corr %>%
  ungroup() %>% 
  filter(x1 %in% c("^IXIC")) %>% 
  filter(abs(corr_time_value) > 0.85) %>% 
  dplyr::mutate(corr_time_value=scales::number(corr_time_value,0.01)) %>% 
  arrange(desc(corr_time_value)) %>% 
  datatable()
```


```{r}
corr_extra = data.frame(x1=all_ids,
                        x2=all_ids,
                        corr_time_value=1)

filtered_cor_df <- df_best_corr %>%
  ungroup() %>% 
  filter(x1 %in% c("^IXIC","M2SL","GDP","CSUSHPINSA","MSPUS","MSPUS","M1SL","	BTC-USD")) %>% 
  filter(abs(corr_time_value) > 0.85)

# Create a nodes data frame
nodes <- data.frame(id = unique(c(filtered_cor_df$x1, filtered_cor_df$x2)), label = unique(c(filtered_cor_df$x1, filtered_cor_df$x2)))

# Create an edges data frame
edges <- filtered_cor_df %>%
  mutate(color = if_else(corr_time_value > 0, "green", "red"),
         width = scales::rescale(abs(corr_time_value),to=c(0,30))) %>%
  dplyr::select(from = x1, to = x2, color, width)

# Create a visNetwork graph
visNetwork(nodes, edges) %>%
  visIgraphLayout() %>%
  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%
  visInteraction(navigationButtons = TRUE)

```

### SPY

```{r}
df_best_corr %>%
  ungroup() %>% 
  filter(x1 %in% c("^GSPC")) %>% 
  filter(abs(corr_time_value) > 0.85) %>% 
  dplyr::mutate(corr_time_value=scales::number(corr_time_value,0.01)) %>% 
  arrange(desc(corr_time_value)) %>% 
  datatable()
```


```{r}
corr_extra = data.frame(x1=all_ids,
                        x2=all_ids,
                        corr_time_value=1)

filtered_cor_df <- df_best_corr %>%
  ungroup() %>% 
  filter(x1 %in% c("^GSPC","GDP","M2SL","MSPUS","PCEPI","CSUSHPINSA","CPIAUCSL","WOOD","WALCL")) %>% 
  filter(abs(corr_time_value) > 0.85)

# Create a nodes data frame
nodes <- data.frame(id = unique(c(filtered_cor_df$x1, filtered_cor_df$x2)), label = unique(c(filtered_cor_df$x1, filtered_cor_df$x2)))

# Create an edges data frame
edges <- filtered_cor_df %>%
  mutate(color = if_else(corr_time_value > 0, "green", "red"),
         width = scales::rescale(abs(corr_time_value),to=c(0,30))) %>%
  dplyr::select(from = x1, to = x2, color, width)

# Create a visNetwork graph
visNetwork(nodes, edges) %>%
  visIgraphLayout() %>%
  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%
  visInteraction(navigationButtons = TRUE)

```



# Case_Shiller Housing

```{r}
df_best_corr %>%
  ungroup() %>% 
  filter(x1 %in% c("CSUSHPINSA")) %>% 
  filter(abs(corr_time_value) > 0.85) %>% 
  dplyr::mutate(corr_time_value=scales::number(corr_time_value,0.01)) %>% 
  arrange(desc(corr_time_value)) %>% 
  datatable()
```


```{r}
corr_extra = data.frame(x1=all_ids,
                        x2=all_ids,
                        corr_time_value=1)

filtered_cor_df <- df_best_corr %>%
  ungroup() %>% 
  filter(x1 %in% c("CSUSHPINSA","GDP","	Enfamiliehuse_Indeks","CPIAUCSL","M2SL","PCEPI","PAYEMS","WOOD","ACTLISCOUUS")) %>% 
  filter(abs(corr_time_value) > 0.85)

# Create a nodes data frame
nodes <- data.frame(id = unique(c(filtered_cor_df$x1, filtered_cor_df$x2)), label = unique(c(filtered_cor_df$x1, filtered_cor_df$x2)))

# Create an edges data frame
edges <- filtered_cor_df %>%
  mutate(color = if_else(corr_time_value > 0, "green", "red"),
         width = scales::rescale(abs(corr_time_value),to=c(0,30))) %>%
  dplyr::select(from = x1, to = x2, color, width)

# Create a visNetwork graph
visNetwork(nodes, edges) %>%
  visIgraphLayout() %>%
  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%
  visInteraction(navigationButtons = TRUE)

```
