---
title: "Release Calendar"
author: "Christian Kruse"
date: "`r Sys.Date()`"
output: html_document
---

```{r  include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
options(scipen=999)
```

```{r}

if (!require(pacman)) { install.packages("pacman") }
pacman::p_load(fredr,
               dplyr,
               tidyr,
               lubridate,
               caret,
               partykit,
               pROC,
               gganimate,
               devtools,
               httr,
               DT,
               httr,
               visNetwork,
               dkstat,
               data.table,
               pROC,
               gridExtra,
               glue,
               igraph,
               visNetwork,
               rPref,
               progress,
               quantmod,
               rvest,
               ggrepel)
source(file = file.path("..", "..", "money_theme.R"))

fred_series_metadata = function(series_id) {
  fredr::fredr_series(series_id) %>%
    dplyr::select(id, title, frequency, units_short,
                  seasonal_adjustment_short, popularity)
}

load_fred_series = function(series_ids, start_date = NULL) {
  series_ids = unique(stats::na.omit(series_ids))
  if (length(series_ids) == 0) {
    return(data.frame())
  }
  data.table::rbindlist(lapply(series_ids, function(series_id) {
    metadata = fred_series_metadata(series_id)
    observations = if (is.null(start_date)) {
      fredr_cached(series_id = series_id)
    } else {
      fredr_cached(series_id = series_id, observation_start = start_date)
    }
    if (nrow(observations) == 0) return(data.frame())
    observations %>%
      dplyr::select(-dplyr::any_of(c("realtime_start", "realtime_end"))) %>%
      tidyr::crossing(metadata)
  }), fill = TRUE)
}

render_series_panels = function(data) {
  if (nrow(data) == 0) {
    cat("No observations are available for this section.")
    return(invisible(NULL))
  }
  for (series in unique(data$series_id)) {
    draw_plots(data = dplyr::filter(data, series_id == series))
  }
}
```

# Release Calendar

```{r }
readRenviron(path = "Renviron.site")
fredr::fredr_set_key(key = Sys.getenv("FRED_API"))
```

```{r}
tag_page_size = 1000
tag_pages = list()
tag_offset = 0
repeat {
  page = fredr::fredr_tags_series(
    "nsa", order_by = "popularity", sort_order = "desc", offset = tag_offset
  )
  tag_pages[[length(tag_pages) + 1]] = page
  if (nrow(page) < tag_page_size || length(tag_pages) >= 20) break
  tag_offset = tag_offset + tag_page_size
}
df_series = do.call("rbind", tag_pages) %>%
  filter(frequency_short %in% c("M", "W", "Q")) %>%
  dplyr::select(id, title, frequency_short, last_updated, popularity)
```

## Function


```{r}
draw_plots = function(data) {

# All time plot

  if (nrow(data) < 2) {
    cat("Not enough observations to calculate indicators for this series.")
    return(invisible(NULL))
  }
  series_id = dplyr::first(data$series_id)
  description = dplyr::first(data$title)
  latest_date = max(data$date, na.rm = TRUE)
  short_window = max(2, min(30, floor(nrow(data) / 2)))
p1 = data %>%
  ggplot(.,aes(x=date,y=value)) +
  geom_line() +
  theme_money_printer_go_brrr(12) +
  scale_x_date(date_labels = "%Y",date_breaks = "5 years") +
  labs(x=NULL, y=NULL, title=description, subtitle=series_id)

# Last year
p2 = data %>%
  filter(date>=Sys.Date()-years(1)) %>%
  ggplot(.,aes(x=date,y=value)) +
  geom_line() +
  theme_money_printer_go_brrr(12) +
  scale_x_date(date_labels = "%b",date_breaks = "1 month") +
  geom_vline(xintercept = latest_date, linetype=2) +
  labs(x=NULL,y=NULL)

# SMA
p3 = data %>%
  arrange(date) %>%
  dplyr::mutate(sma=TTR::SMA(value,n=min(200, n()))) %>%
  dplyr::mutate(deviation=value-sma) %>%
  filter(date>=Sys.Date()-years(1)) %>%
  ggplot(.,aes(x=date,y=deviation)) +
  geom_line() +
  theme_money_printer_go_brrr(12) +
  scale_x_date(date_labels = "%b",date_breaks = "1 month") +
  geom_hline(yintercept = 0,linetype=2) +
  labs(x=NULL,y=NULL)

# RSI
p4 = data %>%
  arrange(date) %>%
  dplyr::mutate(rsi=TTR::RSI(value,n=short_window)) %>%
  filter(date>=Sys.Date()-years(1)) %>%
  ggplot(.,aes(x=date,y=rsi)) +
  geom_line() +
  theme_money_printer_go_brrr(12) +
  scale_x_date(date_labels = "%b",date_breaks = "1 month") +
  geom_hline(yintercept = c(30,70),linetype=2) +
  labs(x=NULL,y=NULL)

  p5 = grid.arrange(p1,p2,p3,p4,ncol=1)
print(p5)

}
```

## All

```{r}
table_limit = 100
selection_limit = 25
df_series %>%
  head(table_limit) %>%
  DT::datatable()
```


```{r}
top_x = df_series %>%
  head(selection_limit) %>%
  pull(id)
```


```{r}
df_data = load_fred_series(top_x)
```

```{r fig.height=20,fig.width=10}
render_series_panels(df_data)
```

## Last week

```{r}
df_series %>%
  filter(last_updated>=Sys.Date()-days(7)) %>%
  DT::datatable()
```

```{r}
top_x = df_series %>%
  filter(last_updated>=Sys.Date()-days(7)) %>%
  head(selection_limit) %>%
  pull(id)
```


```{r}
df_data = load_fred_series(top_x)
```

```{r fig.height=20,fig.width=10}

render_series_panels(df_data)

```


# Unemployment

```{r}

top_x = c("ICSA","UNRATE","CCSA","PAYEMS","CIVPART","HOHWMN02USM065S","CES0500000017","ADPWNUSNERSA","M08343USM232SNBR","LES1252881600Q")
df_data = load_fred_series(top_x)
```



```{r fig.height=20,fig.width=10}

render_series_panels(df_data)

```

## U6 vs UNRATE


```{r}

unrates = c("UNRATE", "U6RATE")
df_u6 = load_fred_series(unrates)

df_u6 %>%
  filter(date>=ymd("1994-01-01")) %>%
  ggplot(aes(x=date,y=value,color=series_id)) +
   geom_line() +
   theme_money_printer_go_brrr(12)


df_u6 %>%
  distinct(series_id,date,value) %>%
  spread(series_id,value) %>%
  arrange(desc(date)) %>%
  dplyr::mutate(diff=U6RATE-UNRATE) %>%
  filter(date>=ymd("1994-01-01")) %>%
  ggplot(aes(x=date,y=diff)) +
   geom_line() +
   geom_hline(yintercept = 0, linetype = 2) +
   theme_money_printer_go_brrr(12)
```
