on:
  push:
     branches:
       - main
  schedule:
    - cron:  '3 0 * * *'

name: money-printer-go-brrr-render

jobs:
  bookdown:
    name: renderbook
    #runs-on: macOS-latest
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Renviron
        run: echo FRED_API=${{ secrets.FRED_API }} >> Renviron.site
      - name: Render Book from Action
        uses: ckrusemd/rmarkdown-action@v0.21
        with:
           input_file: index.Rmd
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/

  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: bookdown
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: _book # optional
        path: _book # optional
    # - name: Deploy to GitHub Pages
    #   uses: Cecilapp/GitHub-Pages-deploy@v3
    #   with:
    #     build_dir: _book/
    #     email: ${{ secrets.EMAIL }}  #optional
    #     jekyll: no                     # optional
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     EMAIL: ${{ secrets.EMAIL }}
    #     BUILD_DIR: _book/
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _book
        user_name: 'GitHub Actions'
        user_email: ${{ secrets.EMAIL }}
        allow_empty_commit: false
        keep_files: true
        force_orphan: true
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Money Printer Go Brrr - Daily Update
        to: ${{secrets.MAIL_USERNAME}}
        from: Christian Kruse
        secure: true
        body: https://ckrusemd.github.io/money-printer-go-brrr/
