on:
  push:
     branches:
       - main
  schedule:
    - cron:  '10 1 * * *' # runs every night

name: money-printer-go-brrr-render

jobs:
  bookdown:
    name: renderbook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Rvest dependencies 1
        run: sudo apt-get update
      - name: Rvest dependencies 2
        run: sudo apt-get -y install xml2 openssl libxml2
      - name: Rvest dependencies 3
        run: sudo apt-get update
      - name: Rvest dependencies 4
        run: sudo apt-get -y install libxml2-dev libmariadb-dev
      - name: Rvest dependencies 5
        run: sudo apt-get update
      - name: Rvest dependencies 6
        run: sudo apt-get -y install libcurl4-gnutls-dev
      - name: Install rvest
        run: Rscript -e 'install.packages(c("pacman"))'
      - name: Renvison 1
        run: echo ${{ secrets.TEST_KEY }}
      - name: Renvison 2
        run: echo ${{ secrets.FRED_API }}
      - name: Renviron
        run: echo FRED_API=${{ secrets.FRED_API }} >> Renviron.site
      - name: Renviron cat
        run: cat Renviron.site
      # - name: Enable Rjava
      #   run: sudo R CMD javareconf
      # - name: Install Rjava before tabulizer
        #run:  Rscript -e 'install.packages("rJava"); library(rJava); install.packages("devtools");devtools::install_github("ropensci/tabulizer", args="--no-multiarch")'
        # run:  Rscript -e 'install.packages("rJava"); library(rJava); install.packages("devtools");'
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown","pacman","devtools","RCurl","rPref","rvest","epibasix","png"))'
      # - name: Install tabulizerjars from source
      #   run:  Rscript -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/tabulizerjars/tabulizerjars_1.0.1.tar.gz", repos = NULL, type="source")'
      # - name: Install tabulizer from source
      #   run:  Rscript -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/tabulizer/tabulizer_0.2.2.tar.gz", repos = NULL, type="source")'
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ hashFiles('DESCRIPTION') }}
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/

  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: bookdown
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: _book # optional
        path: _book # optional
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      with:
        build_dir: _book/
        email: ${{ secrets.EMAIL }}optional
        jekyll: no                     # optional
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EMAIL: ${{ secrets.EMAIL }} 
        BUILD_DIR: _book/
